### ISSUE TITLE
Administrative Hierarchy data using nominatim

### ISSUE THREAD

**Issue by MALKARAJ** [osm-search/Nominatim#3435] opened 2024-06-05 11:27 UTC
Hi Team,
I appreciate your efforts in answering every query and providing support for Nominatim
, **is there any way to get administrative hierarchy data using Nominatim**

for example
**country -> state -> city-> next subdivision**
according to the country

Thanks,
Malkaraj K

**Comment by lonvia** [comment] 2024-06-05 12:27
Duplicate of https://community.openstreetmap.org/t/is-it-possible-to-get-administrative-hierarchy-data-in-osm-using-overpass-api/114135.

**Closed by lonvia** 2024-06-05 12:27 UTC
