### ISSUE TITLE
Update process failed on log entry due to "Uncaught Nominatim\DatabaseError"

### ISSUE THREAD

**Issue by baznikin** [osm-search/Nominatim#2246] opened 2021-03-31 10:40 UTC
**Describe the bug**
Database updated nicely, but failed on adding entry to `import_osmosis_log`.
After restart process continue. It takes 3 runs to complete update.

**To Reproduce**
I build Docker image using https://github.com/mediagis/nominatim-docker and then run it inside Kubernetes.
For this report I run `./src/build/utils/update.php --import-osmosis-all` 3 times, see logs below

**Software Environment (please complete the following information):**
- Nominatim version: git branch v3.6.0
- Postgresql version: 12.6-0ubuntu0.20.04.1
- Postgis version: 3.0.0+dfsg-6ubuntu4
- OS: Ubuntu 20.04.2 LTS

**Hardware Configuration (please complete the following information):**
- RAM: 2Gb
- number of CPUs: 2
- type and size of disks: 100G
- bare metal/AWS/other cloud service: Kubernetes on ESXi on baremetal

**Postgresql Configuration:**

**Additional context**

**Run No. 1 **
```
./src/build/utils/update.php --check-for-updates
New data available (1961 => 1963).
New data available (1961 => 1963).
Currently at sequence 1961 (28/03/2021 20:19:10) - 1 indexed
'/usr/local/bin/pyosmium-get-changes' --server 'http://download.geofabrik.de/russia-updates/' --outfile '/app/src/build/osmosischange.osc' --size 30 '--start-id' 1961
'/app/src/build/osm2pgsql/osm2pgsql' --hstore --latlong --append --slim '--with-forward-dependencies' false '--log-progress' true '--number-processes' 1 --cache 2000 --output gazetteer --style '/app/src/settings/import-full.style' --database nominatim --port 5432 --host 'nominatim-db' --user nominatim '/app/src/build/osmosischange.osc'
2021-03-31 07:58:19  osm2pgsql version 1.4.0 (v3.6.0)
2021-03-31 07:58:19  Database version: 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
2021-03-31 07:58:19  Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
2021-03-31 07:58:19  Parsing gazetteer style file '/app/src/settings/import-full.style'.
Processing: Node(306k 1.1k/s) Way(32k 0.08k/s) Relation(1170 2.1/s)  parse time: 1244s (20m 44s)
2021-03-31 08:19:03  Node stats: total(306171), max(8576762524) in 282s
2021-03-31 08:19:03  Way stats: total(32291), max(923946940) in 409s
2021-03-31 08:19:03  Relation stats: total(1170), max(12512752) in 553s
2021-03-31 08:28:54  Done postprocessing on table 'planet_osm_nodes' in 0s
2021-03-31 08:28:54  Done postprocessing on table 'planet_osm_ways' in 0s
2021-03-31 08:28:54  Done postprocessing on table 'planet_osm_rels' in 0s
2021-03-31 08:28:54  Osm2pgsql took 1835s (30m 35s) overall.
2021-03-31 08:28:54  node cache: stored: 306171(100.00%), storage efficiency: 52.59% (dense blocks: 15, sparse nodes: 229645), hit rate: 8.77%
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database query failed

  thrown in /app/src/lib/DB.php on line 61
string(192) "INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('2021-03-30 20:21:23+00:00',1963,59946496,'2021-03-31 07:58:19','2021-03-31 08:28:54','import')"
```
**Run No. 2 **
```
root@nominatim-cc9995b5d-htfjd:/app# ./src/build/utils/update.php --check-for-updates
New data available (1961 => 1963).
root@nominatim-cc9995b5d-htfjd:/app# ./src/build/utils/update.php --import-osmosis-all
Currently at sequence 1961 (28/03/2021 20:19:10) - 1 indexed
'/usr/local/bin/pyosmium-get-changes' --server 'http://download.geofabrik.de/russia-updates/' --outfile '/app/src/build/osmosischange.osc' --size 30 '--start-id' 1961
'/app/src/build/osm2pgsql/osm2pgsql' --hstore --latlong --append --slim '--with-forward-dependencies' false '--log-progress' true '--number-processes' 1 --cache 2000 --output gazetteer --style '/app/src/settings/import-full.style' --database nominatim --port 5432 --host 'nominatim-db' --user nominatim '/app/src/build/osmosischange.osc'
2021-03-31 09:49:43  osm2pgsql version 1.4.0 (v3.6.0)
2021-03-31 09:49:43  Database version: 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
2021-03-31 09:49:43  Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
2021-03-31 09:49:43  Parsing gazetteer style file '/app/src/settings/import-full.style'.
Processing: Node(306k 16.1k/s) Way(32k 1.19k/s) Relation(1170 30.0/s)  parse time: 85s (1m 25s)
2021-03-31 09:51:08  Node stats: total(306171), max(8576762524) in 19s
2021-03-31 09:51:08  Way stats: total(32291), max(923946940) in 27s
2021-03-31 09:51:08  Relation stats: total(1170), max(12512752) in 39s
2021-03-31 09:51:19  Done postprocessing on table 'planet_osm_nodes' in 0s
2021-03-31 09:51:19  Done postprocessing on table 'planet_osm_ways' in 0s
2021-03-31 09:51:19  Done postprocessing on table 'planet_osm_rels' in 0s
2021-03-31 09:51:19  Osm2pgsql took 96s (1m 36s) overall.
2021-03-31 09:51:19  node cache: stored: 306171(100.00%), storage efficiency: 52.59% (dense blocks: 15, sparse nodes: 229645), hit rate: 8.77%
string(192) "INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('2021-03-30 20:21:23+00:00',1963,59946496,'2021-03-31 09:49:43','2021-03-31 09:51:19','import')"
string(104) "UPDATE import_status SET lastimportdate = '2021-03-30 20:21:23+00:00', indexed=false, sequence_id = 1963"
2021-03-31 09:51:19 Completed download step for 2021-03-30 20:21:23+00:00 in 1.6 minutes
'/app/src/nominatim/nominatim.py' --database nominatim --port 5432 --threads 1 --verbose --host 'nominatim-db' --username nominatim -b
WARNING: Starting indexing boundaries using 1 threads
WARNING: Starting boundaries rank 5 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 5

WARNING: Starting boundaries rank 6 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 6

[SKIP]

INFO: Done 11560 in 696 @ 16.598 per second - rank 30 ETA (seconds): 0.60
INFO: Done 11570 in 697 @ 16.582 per second - rank 30 ETA (seconds): 0.00
WARNING: Done 11570/11570 in 703 @ 16.454 per second - FINISHED rank 30

string(187) "INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('2021-03-30 20:21:23+00:00',1963,NULL,'2021-03-31 09:51:19','2021-03-31 10:21:39','index')"
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database query failed

  thrown in /app/src/lib/DB.php on line 61
```

**Run No. 3 **
```
root@nominatim-cc9995b5d-htfjd:/app# ./src/build/utils/update.php --import-osmosis-all
Currently at sequence 1963 (30/03/2021 20:21:23) -  indexed
'/app/src/nominatim/nominatim.py' --database nominatim --port 5432 --threads 1 --verbose --host 'nominatim-db' --username nominatim -b
WARNING: Starting indexing boundaries using 1 threads
WARNING: Starting boundaries rank 5 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 5

WARNING: Starting boundaries rank 6 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 6

WARNING: Starting boundaries rank 7 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 7

WARNING: Starting boundaries rank 8 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 8

WARNING: Starting boundaries rank 9 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 9

WARNING: Starting boundaries rank 10 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 10

WARNING: Starting boundaries rank 11 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 11

WARNING: Starting boundaries rank 12 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 12

WARNING: Starting boundaries rank 13 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 13

WARNING: Starting boundaries rank 14 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 14

WARNING: Starting boundaries rank 15 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 15

WARNING: Starting boundaries rank 16 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 16

WARNING: Starting boundaries rank 17 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 17

WARNING: Starting boundaries rank 18 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 18

WARNING: Starting boundaries rank 19 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 19

WARNING: Starting boundaries rank 20 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 20

WARNING: Starting boundaries rank 21 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 21

WARNING: Starting boundaries rank 22 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 22

WARNING: Starting boundaries rank 23 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 23

WARNING: Starting boundaries rank 24 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 24

WARNING: Starting boundaries rank 25 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 25

'/app/src/nominatim/nominatim.py' --database nominatim --port 5432 --threads 1 --verbose --host 'nominatim-db' --username nominatim
WARNING: Starting indexing rank (1 to 30) using 1 threads
WARNING: Starting rank 1 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 1

WARNING: Starting rank 2 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 2

WARNING: Starting rank 3 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 3

WARNING: Starting rank 4 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 4

WARNING: Starting rank 5 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 5

WARNING: Starting rank 6 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 6

WARNING: Starting rank 7 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 7

WARNING: Starting rank 8 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 8

WARNING: Starting rank 9 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 9

WARNING: Starting rank 10 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 10

WARNING: Starting rank 11 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 11

WARNING: Starting rank 12 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 12

WARNING: Starting rank 13 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 13

WARNING: Starting rank 14 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 14

WARNING: Starting rank 15 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 15

WARNING: Starting rank 16 (using batch size 1)
INFO: Done 30 in 2 @ 10.853 per second - rank 16 ETA (seconds): 0.64
WARNING: Done 37/37 in 3 @ 11.522 per second - FINISHED rank 16

WARNING: Starting rank 17 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 17

WARNING: Starting rank 18 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 18

WARNING: Starting rank 19 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 19

WARNING: Starting rank 20 (using batch size 1)
WARNING: Done 20/20 in 1 @ 16.672 per second - FINISHED rank 20

WARNING: Starting rank 21 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 21

WARNING: Starting rank 22 (using batch size 1)
WARNING: Done 1/1 in 0 @ 67.856 per second - FINISHED rank 22

WARNING: Starting rank 23 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 23

WARNING: Starting rank 24 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 24

WARNING: Starting rank 25 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 25

WARNING: Starting rank 26 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 26

WARNING: Starting rank 27 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 27

WARNING: Starting rank 28 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 28

WARNING: Starting rank 29 (using batch size 1)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 29

WARNING: Starting rank 0 (using batch size 1)
INFO: Done 80 in 2 @ 36.045 per second - rank 0 ETA (seconds): 7.52
INFO: Done 116 in 3 @ 29.018 per second - rank 0 ETA (seconds): 8.10
INFO: Done 145 in 5 @ 28.218 per second - rank 0 ETA (seconds): 7.30
INFO: Done 173 in 5 @ 29.441 per second - rank 0 ETA (seconds): 6.05
INFO: Done 202 in 6 @ 29.250 per second - rank 0 ETA (seconds): 5.09
INFO: Done 231 in 7 @ 29.817 per second - rank 0 ETA (seconds): 4.02
INFO: Done 260 in 8 @ 29.539 per second - rank 0 ETA (seconds): 3.08
INFO: Done 289 in 9 @ 30.094 per second - rank 0 ETA (seconds): 2.06
INFO: Done 319 in 10 @ 29.987 per second - rank 0 ETA (seconds): 1.07
INFO: Done 348 in 11 @ 30.267 per second - rank 0 ETA (seconds): 0.10
WARNING: Done 351/351 in 11 @ 30.282 per second - FINISHED rank 0

WARNING: Starting interpolation lines (location_property_osmline) (using batch size 20)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED interpolation lines (location_property_osmline)

WARNING: Starting rank 30 (using batch size 20)
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 30

string(181) "INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('30/03/2021 20:21:23',1963,NULL,'2021-03-31 10:22:31','2021-03-31 10:22:49','index')"
2021-03-31 10:22:49 Completed index step for 30/03/2021 20:21:23 in 0.3 minutes
2021-03-31 10:22:49 Completed all for 30/03/2021 20:21:23 in 0.3 minutes
Currently at sequence 1963 (30/03/2021 20:21:23) - 1 indexed
Waiting for next update for 35914 sec.
```

**Comment by lonvia** [comment] 2021-03-31 16:22
Sounds like you have an issue with the database connection. What does the postgresql log say what the error is?

**Comment by baznikin** [comment] 2021-04-01 02:35
> Sounds like you have an issue with the database connection. What does the postgresql log say what the error is?

I don't think so. Scripts chew data for many minutes and instantly fail on same spot every time. I saw this situation every day for every update since Nominatim installed.
Postgres log have no messages at error time, I double checked, no correlation.

**Comment by lonvia** [comment] 2021-04-01 07:06
You can try to get a more extensive error message with this change:

```
diff --git a/lib/DatabaseError.php b/lib/DatabaseError.php
index 3a53bc8f..51a40d6a 100644
--- a/lib/DatabaseError.php
+++ b/lib/DatabaseError.php
@@ -15,7 +15,8 @@ class DatabaseError extends \Exception
 
     public function __toString()
     {
-        return __CLASS__ . ": [{$this->code}]: {$this->message}\n";
+        $sError = $this->getSqlError();
+        return __CLASS__ . ": [{$this->code}]: {$this->message} ({$sError})\n";
     }
 
     public function getSqlError()
```

**Comment by baznikin** [comment] 2021-04-01 08:35
This time there is no error after import ("Run no.1" in logs above), I got this error:

```
INFO: Done 7800 in 344 @ 22.636 per second - rank 30 ETA (seconds): 1.59
INFO: Done 7820 in 344 @ 22.673 per second - rank 30 ETA (seconds): 0.71
INFO: Done 7836 in 345 @ 22.665 per second - rank 30 ETA (seconds): 0.00
WARNING: Done 7836/7836 in 346 @ 22.627 per second - FINISHED rank 30

string(187) "INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('2021-03-31 20:19:59+00:00',1964,NULL,'2021-04-01 08:08:51','2021-04-01 08:25:21','index')"
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database query failed (SQLSTATE[HY000]: General error: 7 server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.)

  thrown in /app/src/lib/DB.php on line 61
```

However, there is absolutely no error messages in postgresql logs! There is many errors like "could not receive data from client: Connection reset by peer" but none at import time...

**Comment by lonvia** [comment] 2021-04-01 09:13
Yes, as I thought. You are having trouble connecting to the server. Both, the client side message and the server side message indicates that. If I had to guess: looks like the server has a very small timeout before it closes connection where no data is sent.

In any case, it is a database administration issue and not a bug in Nominatim, so closing here.

**Closed by lonvia** 2021-04-01 09:13 UTC
