### ISSUE TITLE
Odd search results seemingly caused by ignoring addr:street

### ISSUE THREAD

**Issue by tguen** [osm-search/Nominatim#2816] opened 2022-09-17 23:13 UTC
## What did you search for?

[63033 Highway 101, Coos Bay, 97420](https://nominatim.openstreetmap.org/ui/search.html?street=63033+highway+101&city=coos+bay&postalcode=97420)

## What result did you get?

I get only sections of Highway 101 a bit north of the correct location.

## What result did you expect?

The [correct location](https://www.openstreetmap.org/way/683806146) is returned when searching for [63033, Coos Bay, 97420](https://nominatim.openstreetmap.org/ui/search.html?street=63033&city=coos+bay&postalcode=9742), although the results list the cross-street, Flanagan Road, rather than Highway 101 as it's tagged.

**Comment by lonvia** [comment] 2022-09-18 07:52
`addr:street` needs to refer to a mapped street name for Nominatim or search won't work. In this particular case, Newport Lane is missing the alternative name 'Highway 101' in a name tag. It is there in the tiger_base data only.

NB; any particular reason there are two Oregon Coast Highways (https://www.openstreetmap.org/relation/12140429, https://www.openstreetmap.org/relation/2306824)?

**Comment by lonvia** [comment] 2022-09-22 07:01
I'm closing this as a data issue. I've looked again a bit into the issue of doubly named streets in the US. The problem is that there is no rule how a highway ref is translated into a street name. Pretty much every address I look at uses slightly different formatting. Even if Nominatim would start using road relations to get the proper highway refs, it's not possible to infer the name that is in local use.

You will have to add the highway name as an alternative name to the road (i.e. the `highway` OSM way) in question to make it work. See [This QA view](https://nominatim.org/qa/#map=4.77/38.07/-89.05&layer=addr_street_wrong_name) for a map of addresses where the `addr:street` tag does not match with the street name, if you want to improve the situation in your area.

**Closed by lonvia** 2022-09-22 07:01 UTC

**Comment by tguen** [comment] 2022-09-24 05:15
Ah, the dreaded "closed wontfix"

> `addr:street` needs to refer to a mapped street name for Nominatim or search won't work. 

Why? This seems... very questionable. It's entirely reasonable to expect that it will find an address when searching for the exact tags on the feature. Ignoring `addr:street` tags is obviously causing poor results in this case, despite the data being correct. You may consider it incomplete, but it is absolutely complete enough to find the feature.

**Comment by tguen** [comment] 2022-09-24 05:19
Also, it appears to be guessing which street the address belongs to, possibly based on which street is closest. This is also questionable. It was clearly wrong in this case.
