### ISSUE TITLE
"house" returned from search shows wrong estimated location

### ISSUE THREAD

**Issue by atiannicelli** [osm-search/Nominatim#2804] opened 2022-08-23 14:19 UTC
11 Merrill Street Cambridge

https://nominatim.openstreetmap.org/ui/search.html?q=11+Merrill+Street+Cambridge
![Screen Shot 2022-08-23 at 10 18 04 AM](https://user-images.githubusercontent.com/5851115/186182190-bbc05afe-a6b1-4501-baa4-87774663e3c0.png)

I get two results:

1. The first result is a "building=yes" that correctly identifies the location of the address that I searched for.
2. The second result is a "house" that seems to be an estimate of where it thinks the address should be along this street. After some experimentation it seems that the algorithm thinks that this street should have addresses from 1-99 and the location is just an estimate on that street of where the number I search for is along that section of road. (e.g. If I search for 75 then it locates a place 75% of the way down the street).

My question is: Where does Nominatim come up with this info? Why does it assume that the street addresses are from 1-99 (is that just the default)? How can we get it NOT to return the estimated value if an actual value exists on the street? 

I expected that only the correctly located address would be returned. If the "house" is an estimate then how can a street be edited in OSM to better define the address range of the street? <--- that is more of a hack as we should probably not be adding info to the map to make the search results better.

![Screen Shot 2022-08-23 at 10 15 36 AM](https://user-images.githubusercontent.com/5851115/186181591-b8ddface-cc61-4779-b97d-8efaee8dc5d1.png)

Also, the "details" link in nominatim for this "house" is broken
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=8614860&class=place
The OSM feature is there, but the class=place seems to be a problem.
![Screen Shot 2022-08-23 at 10 16 37 AM](https://user-images.githubusercontent.com/5851115/186181833-b94bf5aa-77d5-4c15-b879-b07ca3a27ea5.png)

**Comment by mtmail** [comment] 2022-08-23 14:28
The second result comes from TIGER data (https://nominatim.org/release-docs/latest/customize/Tiger/), not OpenStreetMap data. With TIGER there are only interpolations (start number, end number on a line string), it doesn't contain exact house numbers and and any number in the range gets calculated to a position at search type on-the-fly.

It's confusing how that is represented in the results and tracked at https://github.com/osm-search/Nominatim/issues/2754

Part of the issue is refuscal to assign TIGER data places a unique id (or osm_type=T) so it points to the street but keeps class=place which has a couple of side effects.

**Comment by lonvia** [comment] 2022-08-29 14:20
Closing as duplicate.

**Closed by lonvia** 2022-08-29 14:20 UTC
