### ISSUE TITLE
Intersection support

### ISSUE THREAD

**Issue by tarunik** [osm-search/Nominatim#3581] opened 2024-11-10 18:47 UTC
**Is your feature request related to a problem? Please describe.**
Nominatim has no idea of what to do with a search for "\<street name\> and \<street name\>, \<rest of address\>".  For instance, "Munich Street & Persia Avenue, San Fransisco, CA".

**Describe the solution you'd like**
A search format of "\<street name\> &/and \<street name\>, \<rest of address\> should give me the intersection of the two streets named, or a list of intersections if the request is ambiguous.

**Describe alternatives you've considered**
If there's a geocoder out there for OSM that already supports this, I'd like to know!

**Additional context**
This would be a monstrously helpful feature both for OSM users (as other mapping tools generally support geocoded searches of intersections) and OSM _mappers_ who are trying to cross-reference from external data sources that often only have street names on them.

**Comment by lonvia** [comment] 2024-11-10 19:26
Duplicate of #123.

**Closed by lonvia** 2024-11-10 19:26 UTC
