### ISSUE TITLE
Searching "Carrer de xxx" returns the wrong result

### ISSUE THREAD

**Issue by Xevib** [osm-search/Nominatim#2036] opened 2020-11-01 16:27 UTC
# Observed problem
- If I search "Carrer València, Girona" https://nominatim.openstreetmap.org/ui/search.html?q=Carrer+Val%C3%A8ncia%2C+Girona&dedupe=0 I get this street https://www.openstreetmap.org/way/84829665 when the expected is this https://www.openstreetmap.org/way/61947463
- If I search "Carrer de València,Girona" I get the correct street link: https://nominatim.openstreetmap.org/ui/search.html?q=carrer+de+Val%C3%A8ncia%2CGirona&dedupe=0

# Question
- If I add the "carrer de" string here it will be fixed? https://github.com/osm-search/Nominatim/blob/26bc83c9844ceba531837bfed79cd51b12a6b45a/module/tokenstringreplacements.inc#L447 

# Why 
- The "Carrer de" is very used in catalan Overpass query https://overpass-turbo.eu/s/ZAQ

**Comment by jmontane** [comment] 2020-11-01 19:27
Hi,

This is an annoying issue for years! Users expect get same results searching for "carrer "+foobar and "carrer de "+foobar.

I made PR #2037 fixing this issue for Catalan ("carrer" lines) and Spanish ("calle" lines) languages. That's for "street" class only-

**Comment by lonvia** [comment] 2020-11-26 13:56
Duplicate of #753.

**Closed by lonvia** 2020-11-26 13:56 UTC
