### ISSUE TITLE
Result depends on the case

### ISSUE THREAD

**Issue by 7171bel** [osm-search/Nominatim#2918] opened 2022-12-08 10:59 UTC
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=2а%2C+МОЛОДЁЖНАЯ+УЛИЦА%2C+РЕЧИЦА%2C+ГОМЕЛЬСКАЯ+ОБЛАСТЬ

## What result did you get?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=239850963&class=building

## What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=174514514&class=building

## Further details
right result when upper case

https://nominatim.openstreetmap.org/ui/search.html?q=2А%2C+МОЛОДЁЖНАЯ+УЛИЦА%2C+РЕЧИЦА%2C+ГОМЕЛЬСКАЯ+ОБЛАСТЬ

**Comment by lonvia** [comment] 2022-12-08 12:56
Duplicate of #2904

**Closed by lonvia** 2022-12-08 12:56 UTC
