### ISSUE TITLE
No match when City name passed

### ISSUE THREAD

**Issue by GeekNJ** [osm-search/Nominatim#3364] opened 2024-03-15 13:38 UTC
## What did you search for?
https://nominatim.openstreetmap.org/ui/search.html?q=1425+woodvine+way%2C+Alpharetta+GA+30005
1425 Woodvine Way, Alpharetta GA 30005

Same result happens using the API. 

## What result did you get?
No match 

## What result did you expect?
A match as the address is in OSM but it appears to not have the city name associated with the address. This lookup returns the expected results:
https://nominatim.openstreetmap.org/ui/search.html?q=1425+woodvine+way%2CGA+30005
1425 Woodvine Way, GA 30005

Is this situation due to improper inheritance of the data in OSM? I would expect the lookup with the city to still find a match. What options are available to handle this as it seems pretty common.

**Comment by lonvia** [comment] 2024-03-17 08:56
The address is outside the the [administrative area of Alpharetta](https://www.openstreetmap.org/relation/119572), so Nominatim cannot know that the city is part of the address without additional information. This is a well-know (but sadly still unresolved) issue with US postal towns, see #1120.

The result for this particular example is also currently not mapped in OSM. The housenumber comes from the supplementary Tiger data, the rest of the address relies on the information Nominatim has about the street. Easiest fix is to add addresses to OSM directly. `addr:city` will be correctly handled for address points.

Closing as duplicate of #1120.

**Closed by lonvia** 2024-03-17 08:56 UTC
