### ISSUE TITLE
I merged Europe and North America Areas and Started extracting. This Error came.

### ISSUE THREAD

**Issue by SoulExtinction** [osm-search/Nominatim#1905] opened 2020-08-05 16:57 UTC
**I have merged North America and Europe OSM files and then tried to extract them.  This error came. Please help me in solving this.**
********************
2020-08-05 01:40:59 == WARNING: resetting threads to 1
2020-08-05 01:40:59 == module path: /srv/nominatim/build/module
2020-08-05 01:40:59 == Create DB
2020-08-05 01:40:59 == Setup DB
Postgres version found: 10
Postgis version found: 2.4
 set_config
------------
 
(1 row)

2020-08-05 01:41:04 == Import data
osm2pgsql version 1.2.0 (v3.5.0-67-g8201c7f)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=46413MB, maxblocks=742608*65536, allocation method=11
Mid: pgsql, cache=46413
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Parsing gazetteer style file '/srv/nominatim/Nominatim/settings/import-full.style'.
Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping

Reading in file: /srv/nominatim/build/europe-north-america.osm.bz2
Using XML parser.
Processing: Node(3824539k 228.0k/s) Way(413495k 49.59k/s) Relation(6198427 5019.0/s)  parse time: 26344s
Node stats: total(3824539161), max(7771142999) in 16771s
Way stats: total(413495830), max(832369740) in 8338s
Relation stats: total(6198427), max(11366925) in 1235s
result COPY END for planet_osm_rels failed: ERROR:  duplicate key value violates unique constraint "planet_osm_rels_pkey"
DETAIL:  Key (id)=(11980) already exists.
CONTEXT:  COPY planet_osm_rels, line 3143

DB copy thread failed: Ending COPY mode
ERROR: No Data
string(7) "No Data"

**Comment by lonvia** [comment] 2020-08-06 06:42
Duplicate of https://help.openstreetmap.org/questions/76029/error-while-extracting-merged-database-for-nominatim-help

**Closed by lonvia** 2020-08-06 06:42 UTC
