### ISSUE TITLE
Removing nominatim.so dependency from PostgreSQL for search/reverse search

### ISSUE THREAD

**Issue by antopaul** [osm-search/Nominatim#1726] opened 2020-03-27 17:59 UTC
I want to use Nominatim in RDS for by importing database dump from another database and use forward and reverse search API. Also I have no plans to do live regular updates. 

Currently this is not possible because of dependency on nominatim.so module. I did some search on the issues and couldn't find anybody attempting to removing nominatim.so from Apache application.

I looked at Geocode.php code and see that its calling **make_standard_name()** function which in turn calls 2 nominatim.so functions - gettokenstring() and transliteration().

Also placex.idx_placex_adminname index is using make_standard_name() function.

I have following questions.
1, Is make_standard_name() only function used by Apache for search and reverse search.
2, Is there any chance of replacing make_standard_name() function with an existing Postgres function which can be slightly slower than nominatim.so? This is needed for the index to work.

Anto

**Comment by lonvia** [comment] 2020-03-27 20:01
Duplicate of #1377. Still no plans to support RDS, sorry.

**Closed by lonvia** 2020-03-27 20:01 UTC

**Comment by TheBaus** [comment] 2022-12-15 10:48
@lonvia Based on the now default [ICU tokenizer](https://nominatim.org/release-docs/latest/customize/Tokenizers/#icu-tokenizer), do you mean RDS is not an officially supported database? Or does the ICU tokenizer now make it supported?

I have managed to get RDS Aurora working with the new tokenizer just for context.

**Comment by lonvia** [comment] 2022-12-15 11:06
RDS probably works these days but there will be no official support unless somebody commissions it.

**Comment by antopaul** [comment] 2022-12-15 12:01
@TheBaus will be grateful if you could share details on how you managed to get Nominatim running in Aurora. 
What Postgres and Nominatim version are used. 
Any additional extensions needs to be installed? 
Any additional Postgres configuration is needed?

**Comment by lonvia** [comment] 2022-12-15 12:39
Closed issues are not the right place to discuss. There is a discussion section for that.
