### ISSUE TITLE
 Error in build  because of missing dependecy in guide: nlohmann

### ISSUE THREAD

**Issue by gsg-git** [osm-search/Nominatim#3192] opened 2023-09-07 13:08 UTC
Hello!
 I got an error: 
"NLOHMANN_INCLUDE_DIR-NOTFOUND"
In the guide is the missing application not mentioned:
nlohmann-json3-dev

Thank you!

**Comment by mtmail** [comment] 2023-09-07 13:11
Just to clarify, which page are you looking at? Is that https://nominatim.org/release-docs/4.3/admin/Installation/ ?

**Comment by lonvia** [comment] 2023-09-07 13:55
Duplicate of #3191.

**Closed by lonvia** 2023-09-07 13:55 UTC
Labels: duplicate
