### ISSUE TITLE
Not finding name that is separated by slash only

### ISSUE THREAD

**Issue by johsin18** [osm-search/Nominatim#2253] opened 2021-04-06 20:49 UTC
## What did you search for?
"Amber Hotel Leonberg"

## What result did you get?
no results

## What result did you expect?
AMBER HOTEL Leonberg/Stuttgart, 102, Römerstraße, Eltingen, Leonberg, Landkreis Böblingen, Baden-Württemberg, 71229, Deutschland Hotel
https://www.openstreetmap.org/way/23881641

**Is the result in the right place and just named wrongly?** 
no

**Is the result missing completely?**
yes

## Further details

Search word "Leonberg" should match "Leonberg/Stuttgart", i.e. the slash should be treated as a separator.  Adding a space to the name would probably help, but we should not "map for the geocoder".

**Comment by lonvia** [comment] 2021-04-14 09:27
That has nothing to do with the slash. The problem is that this is search of a partial name. Nominatim is not particular good on partial matches. That is a long standing and often reported issue.

Closing in favour of #94.

**Closed by lonvia** 2021-04-14 09:27 UTC

**Comment by johsin18** [comment] 2021-05-02 10:58
Searching for just "Amber Leonberg" delivers the expected result, even though it is an even "more partial" match.  Isn't that strange?  So "Leonberg" can be matched, it seems.
