### ISSUE TITLE
Geocoding should prioritize city matches against province matches

### ISSUE THREAD

**Issue by albertvaka** [osm-search/Nominatim#1916] opened 2020-08-09 11:55 UTC
In Spain, provinces share name with the capital city of the province. For example, the city of Barcelona is in the province of Barcelona, the city of Madrid is in the province of Madrid, etc.

This seems to cause problems when geocoding: Searching for the street `Carrer Industria, Barcelona` seems to give higher priority to other streets called "Carrer Industria" in several other cities which are in the _province_ of Barcelona, than the street "Carrer Industria" in the _city_ of Barcelona.

When a name matches both a city (more specific) and a province (less specific), I think the more specific match should take precedence. I think this is always the intended behavior, as someone looking for the "Carrer Industria" in the city of "Sant Feliu de Llobregat" (province of Barcelona) are more likely to search for `Carrer Industria, Sant Feliu de Llobregat`.

I think this is a major problem, since this happens with pretty much every street in Barcelona which has a name that's common enough to also be a street in other cities of the same province (other examples: `Ramon y Cajal, Barcelona`, `Carrer Llibertat, Barcelona`, etc.).

**Comment by lonvia** [comment] 2020-08-11 13:46
Nominatim has the notion of an 'address importance' of a place which is supposed to change the ranking of otherwise equal results by the address parts. Problem is that this importance is only used to sort the final set of results. When there are many results for a given search (for example because 'Carrar Industria' is a very popular name for a street) then this address importance is not helpful because the results set is basically computed from a random subset of all results.

To change this the address importance (aka [`foundorder`]()) needs to be merged with the primary importance of a place, so that it already affects which places are selected in the first place.

**Comment by albertvaka** [comment] 2020-08-15 10:09
Thanks for the detailed explanation. I'm not sure this is exactly the case, though, because a search for "ramón y cajal, barcelona" returns incorrectly sorted results within the first page of results. More specifically, it returns `Residential Road Carrer Ramón y Cajal, Tres Torres, Can Jané, Granollers, Vallès Oriental, Barcelona, Catalonia, 08401, Spain` (city of Granollers, provice of Barceona) before `Residential Road Carrer de Ramón y Cajal, la Vila de Gràcia, Gràcia, Barcelona, Barcelonès, Barcelona, Catalonia, 08001, Spain` (city of Barcelona, provice of Barcelona). Given your explanation, I would expect sorting within the same page to work well.

**Comment by lonvia** [comment] 2020-08-25 20:31
I can't reproduce your findings. Even with the maximum `limit=50` there are no results within Barcelone in the result list. They only show up when asking for 'More results'.

**Comment by albertvaka** [comment] 2020-08-25 21:27
That is the problem :/ why don't we get results for the city of Barcelona when searching "Barcelona" explicitly?

**Comment by matkoniecz** [comment] 2020-08-27 11:39
> I can't reproduce your findings. Even with the maximum limit=50 there are no results within Barcelone in the result list. They only show up when asking for 'More results'.

What about `Długa 12, Kraków` ? 

https://www.openstreetmap.org/search?query=D%C5%82uga+12%2C+Krak%C3%B3w#map=19/50.22996/19.85579

`Dom 12, Długa, Kleparz, Stare Miasto, Old Town, Krakow, Lesser Poland Voivodeship, 31-146, Poland` (that should be on top) is 4th, but listed in initial results 

And it seems that

> When there are many results for a given search (for example because 'Carrar Industria' is a very popular name for a street) then this address importance is not helpful because the results set is basically computed from a random subset of all results.

is not applying here, as real result manages to appear

**Comment by albertvaka** [comment] 2020-08-27 15:24
Indeed @matejkrajcovic this is another example of the same problem I wrote about. Wrong ordering even within the same results page.

**Comment by lonvia** [comment] 2020-08-27 16:39
> What about Długa 12, Kraków ?

Reranking favours the one that matches your input most closely. 'Kraków County' contains the requested `Kraków` exactly. `Krakow` in the result doesn't. [Switch your browser to Polish](https://nominatim.openstreetmap.org/search.php?q=D%C5%82uga%2012%2C%20Krak%C3%B3w&format=jsonv2&accept-language=pl), where the town of Krakow is returned with the accent and the street in Krakow comes first. While there is room for improvement, this is a completely different issue. Regarding the particular case of Polish Powiats, they are imho seriously broken with their English translation. See https://github.com/osm-search/Nominatim/issues/1771#issuecomment-623097693  for details.

**Comment by matkoniecz** [comment] 2020-08-27 19:28
> Regarding the particular case of Polish Powiats, they are imho seriously broken with their English translation. See #1771 (comment) for details.

Thanks, I started https://forum.openstreetmap.org/viewtopic.php?pid=799365#p799365

**Comment by albertvaka** [comment] 2020-08-27 22:20
> 'Kraków County' contains the requested `Kraków` exactly. `Krakow` in the result doesn't. 

I was assuming accents were ignored in search (shouldn't they?). My original issue still stands, though.

**Comment by lonvia** [comment] 2022-04-14 15:55
This needs address importance to be added to general importance. Issue now covered by #2268. Closing here.

**Closed by lonvia** 2022-04-14 15:55 UTC

**Comment by revolution909** [comment] 2023-01-23 14:06
Was the issue solved? I have the same problem

**Comment by matkoniecz** [comment] 2023-01-23 14:09
> This needs address importance to be added to general importance. Issue now covered by https://github.com/osm-search/Nominatim/issues/2268. Closing here.
