### ISSUE TITLE
Forest Heath is in Suffolk, not Cambridgeshire 

### ISSUE THREAD

**Issue by EdwardBetts** [osm-search/Nominatim#2138] opened 2021-01-15 15:53 UTC
## What did you search for?

Forest Heath

https://nominatim.openstreetmap.org/ui/search.html?q=Forest+Heath

## What result did you get?

Forest Heath, Cambridgeshire

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=53356&class=boundary

## What result did you expect?

Forest Heath, Suffolk

**Comment by lonvia** [comment] 2021-01-19 14:17
Duplicate of #2137.

**Closed by lonvia** 2021-01-19 14:17 UTC
