### ISSUE TITLE
Find flat numbers as part of the address search

### ISSUE THREAD

**Issue by Asteliks** [osm-search/Nominatim#1981] opened 2020-09-25 21:40 UTC
This is a request for the ability to find appropriate building entrance ones given the proper flat number. For test you can use this [place](https://www.openstreetmap.org/#map=18/52.20179/20.94914)
Note address Włodarzewska 81-81D, Warszawa

**Comment by lonvia** [comment] 2020-09-26 09:32
Duplicate of #587.

**Closed by lonvia** 2020-09-26 09:32 UTC
Labels: duplicate
