### ISSUE TITLE
Importing full planet: out of space problem

### ISSUE THREAD

**Issue by misbahulhoque** [osm-search/Nominatim#1694] opened 2020-02-23 20:08 UTC
My server H/W specification are below,
RAM: 64 GB
SSD: 1.6 TB
HDD: 4 TB
I was importing full planet osm using a directory where 946 GB was free. FYI, I have not used flatnode. Just imported the full planet pbf using,
./utils/setup.php --osm-file /.../planet-02132020.osm.pbf --all --osm2pgsql-cache 28000 2>&1 | tee setup.log
it took almost 3 whole days and I got the attached image error of no space left on device. 
![Error Running Out of Space](https://user-images.githubusercontent.com/10755555/75119011-cd477a80-5644-11ea-8c46-f41458b5b3d9.jpg)

Now my queries are,
1. How much HDD space I need to be free to import full planet osm?
2. I tried to use flatnode earlier but it shows an error that's why I skipped it. Was it crucial?
3. Is there any solution to the no space problem I can try on my existing imported data ( I have already spent more than 3 days)? Or I have to start from the beginning with the available space required?

Sorry for the huge description. I am in a mess and trying to solve the problem asap. Thanks in advance for your help.

**Comment by lonvia** [comment] 2020-02-23 20:35
There is an issue with Postgresql 12 which runs out of space trying to create indexes concurrently. Not quite sure yet what the root cause is.

Workaround on your existing installation:
1. Edit `sql/indices.src.sql` and `sql/indices_search.src.sql` and remove `CONCURRENTLY` everywhere.
2. Rerun index creation using the following command in the build directory: `./utils/setup.php --create-search-indices --create-country-names`

**Comment by misbahulhoque** [comment] 2020-02-24 03:06
> There is an issue with Postgresql 12 which runs out of space trying to create indexes concurrently. Not quite sure yet what the root cause is.
> 
> Workaround on your existing installation:
> 
> 1. Edit `sql/indices.src.sql` and `sql/indices_search.src.sql` and remove `CONCURRENTLY` everywhere.
> 2. Rerun index creation using the following command in the build directory: `./utils/setup.php --create-search-indices --create-country-names`

Thanks for your reply. Now I am trying to move the imported data into another directory in HDD which has around 1.5 TB free space. Can I then resume the importing process where it encounters no space left problem by re-running the command you have suggested as below?
./utils/setup.php --create-search-indices --create-country-names

**Comment by lonvia** [comment] 2020-02-24 08:34
I wasn't clear enough: if you see the same issue that I saw, then the issue is not that you don't have enough disk space but that Postgresql has a bug. You don't need to free up any space to fix the issue, you only need to avoid creating the indexes concurrently.

**Comment by ankitmlive** [comment] 2020-02-25 07:11
I'm getting an error which is something related to PostgreSQL 12. Rank 27 completed very fast but import running at RANK 30 with lots of slow place_id from 6 to 7 days.here is screenshot ,i have already implemented your setting mentioned here [>>](https://github.com/openstreetmap/Nominatim/issues/1677)

![Screen Shot 2020-02-25 at 12 34 31 PM](https://user-images.githubusercontent.com/25228659/75223216-fba39200-57cb-11ea-92c1-fd490a9faae7.png)


i have restarted servers two times and mine configs are:
Ram : 64GB
SSD : 4TB

**Comment by lonvia** [comment] 2020-02-25 08:33
@ankitmlive This ticket is about out-of-space issues during index creation, so has obviously nothing to do with your problem. You are even referencing the right ticket. Why would you comment on a completely different ticket?

**Comment by ankitmlive** [comment] 2020-02-25 08:50
I am using flat node storage, so assuming that maybe i will get same issue in near future

**Comment by lonvia** [comment] 2020-07-05 15:16
Fixed by reverting concurrent indexing.

**Closed by lonvia** 2020-07-05 15:16 UTC

**Comment by kolorafa** [comment] 2021-11-08 13:52
In the docker enviroment the /dev/shm is limited to 64M by default, while indexing it took way more (rank 20 used 100M)

You can fix that by doing

`docker run --shm-size=1g ...`

or  in `docker-compose.yml`

    shm_size: 1g
    
 Hope it helps someone in the future :)
