### ISSUE TITLE
[amenity=restaurant] plus exact name of the restaurant

### ISSUE THREAD

**Issue by 7171bel** [osm-search/Nominatim#3259] opened 2023-11-26 10:04 UTC
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=%5Bamenity%3Drestaurant%5D+Днепр%2C+Речица

## What result did you get?

No search results found

## What result did you expect?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=1015422910&class=amenity

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by mtmail** [comment] 2023-11-26 12:17
The `[key=value] $place` syntax is undocumented and afaik not officially supported https://nominatim.org/release-docs/latest/api/Search/

It's a shortcut for the so called special phrases https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases For Russian you'd search for `Рестораны в $place` (in) or `Рестораны возле $place` (near). The wiki page lists 20 different word combinations.

The `[key=value] $place` does indeed search for 'in' or 'near' and requires a place name. Searching only for the city shows the restaurant as 4th result.
[[amenity=restaurant] Речица](https://nominatim.openstreetmap.org/ui/search.html?q=%5Bamenity%3Drestaurant%5D+%D0%A0%D0%B5%D1%87%D0%B8%D1%86%D0%B0)

Днепр is already the name of the restaurant so special phrases are not required.
[Днепр, Речица](https://nominatim.openstreetmap.org/ui/search.html?q=%D0%94%D0%BD%D0%B5%D0%BF%D1%80%2C+%D0%A0%D0%B5%D1%87%D0%B8%D1%86%D0%B0)

**Comment by lonvia** [comment] 2023-11-26 20:16
The API currently does not offer restricting results by type. [restaurant Днепр, Речица](https://nominatim.openstreetmap.org/ui/search.html?q=restaurant+%D0%94%D0%BD%D0%B5%D0%BF%D1%80%2C+%D0%A0%D0%B5%D1%87%D0%B8%D1%86%D0%B0) will somewhat do this via category special phrases but also trigger a search for the names.

The [library interface](https://nominatim.org/release-docs/develop/library/NominatimAPI/#nominatim.api.NominatimAPI.search) has a category filter. Maybe the next version of the web API exposes that.

Closing as "works as intended".

**Comment by lonvia** [comment] 2023-11-28 09:11
After reinspecting the code I've come to the conclusion that this is indeed a regression in the Python frontend. The '[]' notation used to restrict the type. The code is wrong.

Reopening.

**Closed** 2023-11-28 19:02 UTC
