### ISSUE TITLE
[Feature Request]: Add oceans / great lakes etc. 

### ISSUE THREAD

**Issue by MarketingPip** [osm-search/Nominatim#2994] opened 2023-03-03 08:33 UTC
It would be great for adding oceans & lakes etc for geo-coding. This could be useful for tracking aerial based objects, boats etc & I would assume a lot more!

I know this has been discussed in issue [#510](https://github.com/osm-search/Nominatim/issues/510) - but this was posted in 2016. So I would assume we could possibly find a cheaper or public data-set etc to use for the project, or map it ourselves the great lakes / oceans etc.

**Comment by lonvia** [comment] 2023-03-03 08:58
Duplicate of #510. It's still open, so no need to repeat, even if the issue is old.

**Closed by lonvia** 2023-03-03 08:58 UTC

**Comment by MarketingPip** [comment] 2023-03-03 09:09
My apologizes @lonvia 🙈 - I didn't realize there was another open issue!
