### ISSUE TITLE
Address node is being parented wrongly

### ISSUE THREAD

**Issue by kubahaha** [osm-search/Nominatim#2814] opened 2022-09-10 15:49 UTC
## What did you search for?

Specific address point: [node 7681142905](https://openstreetmap.org/node/7681142905) - [Nominatim page](https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=7681142905&class=place) is being associated to wrong admin boundary. Initial user report comes from OSM default map *where am I* feature: https://www.openstreetmap.org/search?whereami=1&query=50.68461%2C17.97619#map=19/50.68461/17.97619

## What result did you get?

At admin_level=7 node is associated with [relation 2425787](https://openstreetmap.org/node/2425787) (gmina Turawa) but it is not within it's area.

## What result did you expect?

At admin_level=7 node should be associated with  [relation 2730708](https://www.openstreetmap.org/relation/2730708) (Opole) as  it's within it's area.

## Further details

For better visibility see this [Overpass query](https://overpass-turbo.eu/s/1lM8).

**Comment by lonvia** [comment] 2022-09-13 14:45
This is an update issue. We get wrong intersection information because node changes are not propagated to ways and relations.

Specifically, somebody has moved [this node](https://www.openstreetmap.org/node/10008558754) while editing Rozmarynowa street. As the node is also part of the relation for gmina Turawa, the geometry of the administrative boundary was changed as well in OSM. Nominatim didn't see the geometry change because it does not propagate changes from nodes to relations. So in the Nominatim database we now have Rozmarynowa street which goes a little bit into the gmina Turawa relation and therefore gmina Turawa shows up in all addresses related to Rozmarynowa street. After that it boils down to another case of #2658.

**Comment by lonvia** [comment] 2022-09-14 07:42
Closing this as a combined duplicate of #2563 and #2658.

**Closed by lonvia** 2022-09-14 07:42 UTC
