### ISSUE TITLE
504 Gateway Time-out from search result

### ISSUE THREAD

**Issue by Romeo-PHILLIPS** [osm-search/Nominatim#3065] opened 2023-05-25 07:44 UTC
## What did you search for?
https://nominatim.openstreetmap.org/search?q=Route+de%2C+45220%2C+France&format=json&countrycodes=FR&addressdetails=1&accept-language=en&extratags=True&polygon_geojson=1

## What result did you get?
504

## What result did you expect?
A response

**When the result missing completely:**

**Comment by mtmail** [comment] 2023-05-25 08:52
Essentially duplicate of https://github.com/osm-search/Nominatim/issues/2979

**Closed** 2023-05-25 09:01 UTC
