### ISSUE TITLE
osmline_update update issue psycopg2.errors.InternalError_: line_substring: 1st arg isn't a line

### ISSUE THREAD

**Issue by JumpyWizard404** [osm-search/Nominatim#3092] opened 2023-06-21 06:58 UTC
**Describe the bug**
Hello Everyone, it we have started seeing an issue with our nominatim update process we are running a full replication that is constantly running as described in https://nominatim.org/release-docs/latest/admin/Update/ but as of 4 days ago any time an update it attempted it would fail with
2023-06-21 08:34:02: Starting interpolation lines (location_property_osmline) (using batch size 20)
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 196, in run
    self._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 161, in _update
    indexer.index_full(analyse=False)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
    if self.index_by_rank(26, 30) > 1000:
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 178, in index_by_rank
    total += self._index(runners.InterpolationRunner(analyzer), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 237, in _index
    LOG.info("Wait time: fetcher: %.2fs,  pool: %.2fs",
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 235, in __exit__
    self.finish_all()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 184, in finish_all
    while not thread.is_done():
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 159, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.errors.InternalError_: line_substring: 1st arg isn't a line
CONTEXT:  PL/pgSQL function osmline_update() line 113 at assignment

it seems that osm_line is expecting  line geometry but is receiving something else which causes the update process to fail

**To Reproduce**
The issue gets reproduced anytime you run nominatim update from the project directory i have reproduced it 100% of the time by running: nominatim NOMINATIM_REPLICATION_MAX_DIFF=5000 nominatim replication --catch-up --threads 15

**Software Environment (please complete the following information):**
- Nominatim version: 4.2.1
- Postgresql version: 14.7.1
- Postgis version: 3.3.3
- OS: Debian 11

**Hardware Configuration (please complete the following information):**
- RAM: 16GB
- number of CPUs: 4
- type and size of disks: 750GB Hard Disk

**Postgresql Configuration:**
shared_buffers = 1GB
maintenance_work_mem = 256MB
autovacuum_work_mem = 256MB
work_mem = 64MB	
effective_cache_size = 4GB
synchronous_commit = off
max_wal_size = 512MB
min_wal_size = 80MB
checkpoint_timeout = 5min
checkpoint_completion_target = 0.8

**Nominatim Configuration:**
NOMINATIM_FLATNODE_FILE="/srv/nominatim/flatnode.file"

**Comment by lonvia** [comment] 2023-06-21 08:25
Duplicate of #3036. Please also take note of https://github.com/osm-search/Nominatim/issues/3036#issuecomment-1516569217

**Closed by lonvia** 2023-06-21 08:25 UTC

**Comment by JumpyWizard404** [comment] 2023-06-21 08:43
#3036 doesnt solve the issue i have ran nominatim refresh --functions and the issue is still happening would upgrading to 4.2.3 solve this potentially?
