### ISSUE TITLE
Add "unit" query parameter in structured search

### ISSUE THREAD

**Issue by ARitz-Cracker** [osm-search/Nominatim#1992] opened 2020-10-03 21:25 UTC
Currently, if I want to get the location of a Terrance, which has a unit number instead of its own address, I'd have to search for its address without its unit number, repeat searches for the same address, and keep appending what I don't want onto `exclude_place_ids` until I either find what I'm looking for, or the result ends up not being a building.

I agree that parsing a free-form query for that would be extremely hard and inconsistent, but in situations where we have a separate user-input for "unit number", shouldn't Nominatim have a way to search for the `unit` address tag?

**Comment by ARitz-Cracker** [comment] 2020-10-03 21:37
when I enabled `debug`, I can see that all the units appear to exist in `Pre-filter results`, but Nominatim picks the first one result after `Post-filter results`. The easiest workaround appears to be to make sure that the `limit` parameter is actually respected.

**Comment by mtmail** [comment] 2020-10-03 22:14
support for unit numbers is tracked in https://github.com/osm-search/Nominatim/issues/1992

**Comment by lonvia** [comment] 2020-10-05 14:36
`dedupe` is the relevant parameter here.

Closing as duplicate of #587.

**Closed by lonvia** 2020-10-05 14:36 UTC
