### ISSUE TITLE
Multiple instances of  places not inheriting state-level data in Australia

### ISSUE THREAD

**Issue by patelmm79** [osm-search/Nominatim#2033] opened 2020-10-30 05:04 UTC
Identifying a few cases of missing state data in certain locations, which should be inherited from admin levels.

For example:

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=113322767&class=place

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=365948557&class=amenity

Please advise as to what the problem might be, there are many other instances.

**Comment by lonvia** [comment] 2020-10-30 08:23
Duplicate of #2017.

**Closed by lonvia** 2020-10-30 08:23 UTC
Labels: duplicate

**Comment by patelmm79** [comment] 2020-10-30 16:36
> Duplicate of #2017.

Hi Sarah,  you have been very good about providing guidance as to these issues.  You mentioned a re-import, possible to have more information on that (is it posted anywhere?)

I'm pulling and reviewing a good amount of data, and I'd like to contribute to scalable corrections whenever possible  to ensure that the administrative data is correct and consistently populated.  I've come across issues in Japan, India, Thailand amongst others.

One question I have-- I understand that the "new method" of tagging info for administrative boundaries is to link it to a label node....however I have not been able to find a document that cleanly describes this process.  I've tried to do so via the UI, but it's confusing how to do so there.
