### ISSUE TITLE
address is assigned incorrect suburb

### ISSUE THREAD

**Issue by camelCaseNick** [osm-search/Nominatim#1886] opened 2020-07-21 19:55 UTC
[way/82013591](https://www.openstreetmap.org/way/82013591) (Husumer Straße 33, 20249 Hamburg) lies within [relation/180540](https://www.openstreetmap.org/relation/180540) (Hamburg-Eppendorf) and not [relation/180534](https://www.openstreetmap.org/relation/180534) (Hamburg-Hoheluft-Ost), but Nominatim evaluates it to be in Hamburg-Hoheluft-Ost. [[1]](https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=82013591&class=building)

It might come from the size differences between Eppendorf and Hoheluft-Ost, so the building is closer to the one center than to the center of the relation it is in?

**Comment by mtmail** [comment] 2020-07-21 20:08
The street (https://www.openstreetmap.org/way/5229056) crosses the boundary between the two suburbs. Splitting it at the crossing should work.

**Comment by lonvia** [comment] 2020-07-24 15:26
Duplicate of #785.

**Closed by lonvia** 2020-07-24 15:26 UTC
