### ISSUE TITLE
Partially wrong address

### ISSUE THREAD

**Issue by Juanjo-MC** [osm-search/Nominatim#2446] opened 2021-09-16 15:00 UTC
[Refugio Jou de los Cabrones](https://nominatim.openstreetmap.org/ui/search.html?q=refugio+jou+de+los+cabrones)

## What result did you get?

I got the correct result but the address is partially wrong. Village, municipality and state are wrong:

Village = Camaleño
Municipality = Liébana
State = Cantabria

## What result did you expect?

Village = Bulnes
Municipality = Cabrales
State = Asturias / Asturies

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

## Further details

I guess that the wrong values are assigned because the closest named way, **_Cabaña Verónica-Urriellu_**, is indeed (partially) located within that municipality and state but, in this case, the municipality and state on which the alpine hut is located should take precedence.

**Comment by lonvia** [comment] 2021-09-18 13:42
Just add the appropriate `addr:*` tags and things should fix themselves.

**Comment by lonvia** [comment] 2021-09-18 13:52
Hmm, but #2082 should have fixed that. Please hold off with changes while I investigate.

**Comment by lonvia** [comment] 2021-09-18 14:56
So, the problem is that we have partial `addr:*` tags here. Nominatim will only do the geographic correction of the address parts when no address is present at all. This might be something fixable. If you remove the existing `addr:city=Bulnes`, you'll get the address as stated [on the website of the cabana](http://www.refugiojoudeloscabrones.com/Contacto): 33554 Cabrales, Asturias.

Nominatim won't display a village name of 'Bulnes' because that does not exist in the OSM data. There is only 'Bulnes de Arriba' and 'Bulnes de Abajo'.

Regarding `Municipality = Liébana` it looks like we have to change the meaning of admin levels for Spain and move admin_level 7 to county level.

**Comment by lonvia** [comment] 2021-09-24 21:29
#2447 fixes the assignments, so that now the right state and municipality gets assigned. 'Liebana' remains in the address because there is no admin_level=7 boundary that could overwrite it. That's a known issue discussed elsewhere (and also mentioned in #2447). #2449 adjusts the address rank for boundaries in Spain. Closing here.

**Closed by lonvia** 2021-09-24 21:29 UTC
