### ISSUE TITLE
placex.extratags can be {}, that should be treated same as empty/null

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#3055] opened 2023-05-08 22:59 UTC
The `extratags` in the `placex` table is of [hstore column type](https://www.postgresql.org/docs/14/hstore.html). A place having no extratrags usually has the value set to NULL. But in rare cases I see an empty hash instead.

```sql
SELECT count(*) FROM placex WHERE country_code='us' AND extratags IS NULL;
41491262

SELECT count(*) FROM placex WHERE country_code='us' AND hstore_to_json(extratags)::text = '{}';
5
```

Globally I see about 100 cases, with small variations between servers (all same version and date imported). Example list: 
[nominatim_extratags_to_json_is_{}.txt](https://github.com/osm-search/Nominatim/files/11425732/nominatim_extratags_to_json_is_.txt)

Mont in Belgium is an example where extratags are {}.
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=12888294

```
SELECT extratags, extratags is null, hstore_to_json(extratags)::text FROM placex WHERE osm_type='R' and osm_id=12888294;
 extratags | ?column? | hstore_to_json
-----------+----------+----------------
           | f        | {}
```

This leads to the JSON output having extratags returned as empty array (`[]`) instead of the expected empty hash (`{}`).

https://nominatim.openstreetmap.org/lookup?osm_ids=W76404827&format=jsonv2&extratags=1

```
nominatim lookup --id W76404827 --extra | jq '.'
[
  {
    "display_name": "Sahibabad, Ghaziabad District, Uttar Pradesh, India",
    "place_rank": 19,
    "category": "place",
    "type": "village",
    ...
    "extratags": []
  }
```

For the PHP implementation a fix might be in `PlaceLookup.pm` near
```php
    if ($aPlace['extra']) {
        $aPlace['sExtraTags'] = json_decode($aPlace['extra'], true);
    } else {
        $aPlace['sExtraTags'] = (object) array();
    }
```
and change it to
```php
    if ($aPlace['extra'] && $aPlace['extra'] !== '{}' ) {
```

**Comment by lonvia** [comment] 2023-05-09 08:44
We should track down the root cause why there are empty extratags.

Otherwise I'm leaning towards declaring this a won't fix for PHP and making sure it is correct in the new Python implementation.

**Comment by mtmail** [comment] 2023-05-09 13:23
I updated the database on one server (`UPDATE placex SET extratags = NULL WHERE osm_type IN ('R','W') AND hstore_to_json(extratags)::text = '{}';`) and will check if it happens again to a place. Maybe that helps tracking it down.

**Comment by lonvia** [comment] 2024-02-07 18:18
I can see this happening when a place is unlinked from its administrative relation. The relation then has the artificial `linked_place` tag removed from extratags. If there was no other tag, an empty hstore remains.

**Closed** 2024-02-08 13:26 UTC
