### ISSUE TITLE
An address search (USA) isn't finding the town.  Name is changing in debug.

### ISSUE THREAD

**Issue by brad-4k** [osm-search/Nominatim#2459] opened 2021-10-05 23:14 UTC
## What did you search for?

222 Maurin Rd, Chehalis, Lewis County, WA, 98532

https://nominatim.openstreetmap.org/ui/search.html?q=222+Maurin+Rd%2C+Chehalis%2C+Lewis+County%2C+WA%2C+98532

## What result did you get?

It didn't find the address.  When I select the [debug output](https://nominatim.openstreetmap.org/search.php?q=222+Maurin+Rd%2C+Chehalis%2C+Lewis+County%2C+WA%2C+98532&format=jsonv2&debug=1) option it appears as if it changes the town name to **_chealis_**.

## What result did you expect?
https://nominatim.openstreetmap.org/ui/search.html?q=222%2C+Maurin+Road%2C+Lewis+County%2C+Washington%2C+98532%2C+United+States

**When the result in the right place and just named wrongly:** 
No, it didn't find a location.

**When the result missing completely:**

**Comment by lonvia** [comment] 2021-10-06 07:13
You'll notice in the result shown in your second link that Nominatim doesn't recognize that Maurin Road is in Chehalis. That has something to do with US postal cities, see #1120. We have [this](https://www.openstreetmap.org/relation/237445) as city boundary As Nominatim requires all parts of your search query to be present, nothing is found.

I'm closing this as a duplicate of #1120 as the postal city tagging is the essential problem that needs to be solved to fix this.

NB: the name change in the debug output is just part of the ordinary normalisation process for names. The city name would be normalised in the same way before being saved in the search index and therefore it would match.

**Closed by lonvia** 2021-10-06 07:13 UTC
