### ISSUE TITLE
Wrong county, wrong state

### ISSUE THREAD

**Issue by Megachip** [osm-search/Nominatim#1832] opened 2020-06-14 21:46 UTC
Should be Brandenburg, Potsdam-Mittelmark, Rabenstein/Fläming
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.009401&lon=12.566986&zoom=42&accept-language=en&addressdetails=1
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.016163&lon=12.577972&zoom=42&accept-language=en&addressdetails=1
https://nominatim.openstreetmap.org/reverse?format=json&lat=51.997565&lon=12.553253&zoom=42&accept-language=en&addressdetails=1

**Comment by mtmail** [comment] 2020-06-14 22:14
The center point of the way segment happens to be on the other side of the state border https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=289072683&class=highway (blue circle). That isn't rechecked at search time. One solution is to cut the way into two segments at the state border.

**Comment by lonvia** [comment] 2020-06-15 06:47
Duplicate of #785. 

Please check for duplicates before reporting bugs. Thank you.

**Closed by lonvia** 2020-06-15 06:47 UTC

**Comment by Megachip** [comment] 2020-06-16 22:17
> The center point of the way segment happens to be on the other side of the state border https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=289072683&class=highway (blue circle). That isn't rechecked at search time. One solution is to cut the way into two segments at the state border.

Thanks a lot, now I understand a bit more, how nominatim works. So I'll guess https://nominatim.openstreetmap.org/reverse?format=json&lat=52.194982&lon=13.388214&zoom=42&accept-language=en&addressdetails=1 is the same issue and splitting the street at the boarders will fix the resolution?
