### ISSUE TITLE
US postcode 35437 deleted from OSM data is still returned by Nominatim API

### ISSUE THREAD

**Issue by MoiraPrime** [osm-search/Nominatim#2409] opened 2021-07-29 02:40 UTC
## What did you search for?
"Ellisville, MS"
https://nominatim.openstreetmap.org/ui/search.html?q=Ellisville%2C+MS

## What result did you get?
"Ellisville, Jones County, Mississippi, 35437, United States"

## What result did you expect?
Ellisville, Jones County, Mississippi, **39437**, United States

**Is the result in the right place and just named wrongly?** 

I guess you could say that. It's pointing to the right place, but for some reason the completely wrong zip code.

**Is the result missing completely?**

No

Link to town's relation: https://www.openstreetmap.org/relation/12350513

## Further details

The website says
"Nightly calculated from nearby places having this postcode. Documentation. You can search for those with an Overpass Turbo query." 
but the overpass turbo query for the postcode 35437 returns zero results. All buildings and places I've added nearby in the town are set to 39437.  I can't figure out where this postcode is coming from

**Comment by lonvia** [comment] 2021-07-29 07:39
Looks like postcodes that no longer exist aren't correctly deleted from the `location_postcode` table anymore. Possibly a regression introduced with #2360.

**Comment by lonvia** [comment] 2021-07-31 09:13
I did some further research and it turns out, the postcode comes from our external Tiger-based postcode data.  I can't find any reference to this postcode anywhere, so I presume it was a simple typo and have removed it completely from the file now. Things should sort themselves out over time when data gets updated.

The US postcode list really could do with some updating. @mtmail, do you think we could add a function to our Tiger processing script to also recompute the postcode centroids? Or do we have a better source for postcodes?

**Comment by mtmail** [comment] 2021-07-31 15:23
I'll have a look. We haven't documented how the US postcode data got created. https://www.nominatim.org/release-docs/develop/develop/data-sources/

**Comment by mtmail** [comment] 2021-08-03 13:48
Tiger-based seems the best approach. I created https://github.com/osm-search/TIGER-data/issues/9 as follow-up. While there's many free datasets their licenses aren't clear enough.

**Comment by lonvia** [comment] 2021-08-11 14:21
Okay, thanks. Closing here in favour of the TIGER-data ticket.

**Closed by lonvia** 2021-08-11 14:21 UTC
