### ISSUE TITLE
C/ should be a shortcut for street in spanish, plus some similar issues

### ISSUE THREAD

**Issue by tambetvali** [osm-search/Nominatim#2912] opened 2022-12-02 13:48 UTC
Some inconsistencies with searches:

https://nominatim.openstreetmap.org/ui/search.html?q=c%2F+Marie+Curie%2C+20%2C+Barcelona%2C+Spain
C/ is spanish short for "carrer", a street. Nominatim is not very consistent in understanding this.
https://nominatim.openstreetmap.org/ui/search.html?q=carrer+Marie+Curie%2C+20%2C+Barcelona%2C+Spain - this is the correct answer (with "carrer" written out).

It doesn´t find the house number "9" at carrer Número 60 Zona Franca:
https://nominatim.openstreetmap.org/ui/search.html?q=carrer+N%C3%BAmero+60+Zona+Franca%2C+9
Still it finds the street itself:
https://nominatim.openstreetmap.org/ui/search.html?q=carrer+N%C3%BAmero+60+Zona+Franca

https://nominatim.openstreetmap.org/ui/search.html?q=carrer+Robadors%2C+7
Robadors, 7 gives quite consistently script timeout. Again, it finds the street:
https://nominatim.openstreetmap.org/ui/search.html?q=carrer+Robadors
i guess it's the right street as google maps gives the same (and there it is actually). Then it's spelled a bit incorrectly, but i have this in my list so i raport just in case, it's interesting thing a consistent script timeout.

Av. Drassanes, 13-15
Next consistent timeout. 13-15 means that you can use all doors from 13 to 15 (it should give something in the middle as a point value?).

c/ Riereta, 24 - also a consistent script timeout.
https://nominatim.openstreetmap.org/ui/search.html?q=c%2F+Riereta%2C+24%2C+barcelona%2C+spain
Whereas carrer instead of c/ gives the right place:
https://nominatim.openstreetmap.org/ui/search.html?q=carrer+Riereta%2C+24%2C+barcelona%2C+spain

c/ Elisa, 21, barcelona, spain gives results in Mexico, when searched with my script. carrer Elisa gives the right one (carrer d'Elisa). There might become more similar queries, but I give this list right now:
- c/ in spanish is a shorthand for carrer. It should work. Right now I will set it to automatically replace c/ and C/ with carrer.
- 13-15 means that all those doors (numbered on street) lead to the same place.
- carrer Número 60 Zona Franca contains a number in the street name itself, this might be a problem.

**Comment by lonvia** [comment] 2022-12-10 15:57
#### Carrer de Marie Curie

"carrer" is Catalan and we already have the `carrer` -> `c/` abbreviation: https://github.com/osm-search/Nominatim/blob/8a0b2dc0be914c8da8eab1359349151c5a4c6054/settings/icu-rules/variants-ca.yaml#L22

The problem here is the stop word `de`. This is already covered in #753.

#### carrer Número 60 Zona Franca, 9

This is a data issue. 'Zona Franca' is not in OpenStreetMap. Neither is house number 9 for `carrer Numero 60`. The search without housenumber gets you a fire station with 'Zona Franca' in its name.

#### carrer Robadors, 7

I cannot reproduce the script timeouts. The street is called 'Carrer d'en Robador'. Note the missing 's' in the end. Missing spelling correction is already covered in #759.

#### Av. Drassanes, 13-15

Missing housenumber data.

#### c/ Riereta, 24

The only real bug because the result is returned when spain is removed. Alrady covered in issue as #2506.

#### c/ Elisa, 21, barcelona, spain gives results in Mexico

Again not reproducible. Are you sure you are using Nominatim?

**Comment by tambetvali** [comment] 2022-12-12 10:30
Thanks for your replies,

I'm using Nominatim in the following manner (for your last question) from Python scripting language:

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="Custom Python Script")
geocode = lambda query: geolocator.geocode("%s, Barcelona, Spain" % query)
location = geolocator.geocode(insert_address_here)

Lambda query is adding "Barcelona, Spain" automatically to the end of every search, so it should not give result in mexico.


from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="Custom Python Script")
geocode = lambda query: geolocator.geocode("%s, Barcelona, Spain" % query)
location = geolocator.geocode("c/ Elisa, 21")
print(location)

This returns:
Calle Elisa, Benito Juárez, Ciudad de México, 03500, México

Can I have as well defined search range near something - having one area on map, and when the result is closer to that area, this is better?

Right now I added my addresses manually, this automatic script yields several results in odd places and is not reliable.

**Comment by tambetvali** [comment] 2022-12-12 10:33
"Robadors, 7" now gave "None" instead of script timeout.

Av. Drassanes still gives script timeout:

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="Custom Python Script")
geocode = lambda query: geolocator.geocode("%s, Barcelona, Spain" % query)
location = geolocator.geocode("Av. Drassanes, 13-15")
print(location)

Result:

Traceback (most recent call last):
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1369, in getresponse
    response.begin()
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 341, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 828, in urlopen
    **response_kw
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 828, in urlopen
    **response_kw
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Av.+Drassanes%2C+13-15&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\adapters.py", line 457, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Av.+Drassanes%2C+13-15&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/troballa/Desktop/Adreces_Recursos/nominatim_test.py", line 5, in <module>
    location = geolocator.geocode("Av. Drassanes, 13-15")
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\adapters.py", line 447, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "C:\Users\troballa\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\adapters.py", line 469, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Av.+Drassanes%2C+13-15&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

**Comment by lonvia** [comment] 2022-12-12 10:49
I'm sorry, I can't help you with the geopy script. I can just tell you that your lambda trick is most likely not doing its job and that the timeouts are a result of you violating the [usage policy](https://operations.osmfoundation.org/policies/nominatim/).

 If you have a search result which you believe is a bug, then please first go to https://nominatim.openstreetmap.org and confirm that you see the same issues there. Then open a bug report using the appropriate template for search issue and follow the instructions (in particular the one which tells you to check if the data is in OpenStreetMap).

Closing here as issues raised are either not valid or already have an open ticket.

**Closed by lonvia** 2022-12-12 10:49 UTC

**Comment by tambetvali** [comment] 2022-12-12 13:44
The lambda trick is from the manual. Which is the usage policy I break?

**Comment by mtmail** [comment] 2022-12-12 13:54
geopy is a separate project. My guess is the "maximum of 1 request per second" limit it triggered too often.
