### ISSUE TITLE
Nominatim on osm.org gives out of memory when requesting 'japan' with geometry

### ISSUE THREAD

**Issue by pietervdvn** [osm-search/Nominatim#2928] opened 2022-12-18 21:14 UTC
The following request fails with a cryptic 'out of memory'-exception: https://nominatim.openstreetmap.org/search.php?q=Japan&polygon_geojson=1&format=jsonv2

**Comment by lonvia** [comment] 2022-12-23 18:45
I was able to reproduce this when it was reported but, oddly enough, this seems to have fixed itself in the meantime. So I suspect there really was a bug but I can't do anything about it now. Closing as 'not reproducible'. Feel free to reopen if you run into another case.

**Comment by viktor-wolf** [comment] 2023-05-21 20:28
This seems to have become a problem again.

Searching for "Japan" on https://nominatim.openstreetmap.org/ results in a "Error fetching data from /search.php?q=japan&polygon_geojson=1&format=jsonv2" error.

The output from the API request in the error message is below:

```json
{
    "error": {
        "code": 500,
        "message": "Allowed memory size of 209715200 bytes exhausted (tried to allocate 10485760 bytes)"
    }
}
```

Changing the polygon_geojson value to 0 produces a seemingly correct response.

**Comment by lonvia** [comment] 2023-05-21 22:16
That's a duplicate of #2987. nominatim-ui should probably force a polygon_threshold.

**Closed by lonvia** 2023-05-21 22:16 UTC
