### ISSUE TITLE
Street Suffix Matching

### ISSUE THREAD

**Issue by d3mon187** [osm-search/Nominatim#1988] opened 2020-10-01 19:06 UTC
I'm currently building a new Nominatim server to replace a server with a very old Nominatim version.  The new version seems to do a better job of matching in general, but I noticed that it doesn't seem to match if the street suffix is removed.  For example, I live on a street that ends in the suffix "St.", but it is commonly found in data like OSM to be "Lane".  I usually get around bad matches like this by searching Nominatim without the suffix like "123 Fake" instead of "123 Fake St", and then my old Nominatim will return "123 Fake Ln".  My new server however will just show no matching results.  I've verified that both have the same OSM ID record, but the old version will return the osm id without the suffix while the new one will not.  Is this something that changed, or is there a setting/syntax that allows this? Thanks!

**Comment by mtmail** [comment] 2020-10-01 19:11
Do you see the same on nominatim.openstreetmap.org? Can you post 2-3 full queries/URLs and the expected OSM object?

**Comment by d3mon187** [comment] 2020-10-01 20:36
Ok, so I think a better question is what kind of wizardry is going on in Nominatim's partial matching?  ;D  
I don't want to post my home address, or too many other random residential addresses, but it seems to be a coin toss on whether Nominatim will match without the suffix.  Good thing is that the new version actually seems to match better without suffixes, and of course it just figures that my house is one of the few ones where the old version works better.  My new server does match the online version behavior though.

I did manage to find a random street though that doesn't match at all in the new version, but does in the old. - 
https://nominatim.openstreetmap.org/ui/search.html?street=Guinevere+Ln&city=austin&county=TX&country=US&postalcode=78746

Here's another random address where "iron stone" matches on the old server, but only "iron stone ln" matches on the new version. - https://nominatim.openstreetmap.org/ui/search.html?street=iron+stone&city=san+antonio&county=TX&state=&country=US&postalcode=78230

**Comment by mtmail** [comment] 2020-10-02 15:17
Nominatim doesn't do partial string matching. It normalizes "Some Lane" into "Some Ln" (https://github.com/osm-search/Nominatim/blob/master/module/tokenstringreplacements.inc), same for Street->St and for many languages and then does the same transformation during query time with the address the user submitted. There's flaws and edge cases with that approach, missing items, overlaps between languages, and it should be rewritten at some point (https://github.com/osm-search/Nominatim/issues/1208). The logic hasn't changes in last years.

Nominatim doesn't recognize Guinevere Lane as inside Austin
https://www.openstreetmap.org/way/15382674
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=15382674

The official boundaries of Austin are surprising https://www.openstreetmap.org/relation/113314 It's the same with many US cities where the official boundaries don't match with user or resident expectation. Las Vegas https://www.openstreetmap.org/relation/170117 is another example.

Street marked as star:
![image](https://user-images.githubusercontent.com/3727288/94939446-75260000-04d2-11eb-8e6d-cf540dedecc6.png)

There's been some progress recently https://github.com/osm-search/Nominatim/pull/1965 but I think the street https://www.openstreetmap.org/way/15382674 would need an `addr:city` tag. I can't explain why the query worked in older Nominatim versions.

**Comment by d3mon187** [comment] 2020-10-02 18:30
Oh ok, I missed that Guinevere had been updated recently, and I had stopped updates on the old server which lists it as being in Austin.  Thanks for the insight!

It seems like for the Iron Stone search, that Nominatim will return "Ln" and "Ct" results on "Iron Stone" only if you omit either the city or the postcode.  If you include both then it will return no results.  The old version doesn't seem to have that issue.  I also noticed that the new version is lacking postcodes for some addresses.  "[Iron Stone Ln](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=15136240&class=highway)" for example shows the zipcode, but "[Iron Stone Ct](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=15136240&class=highway)" does not.  On my old version it does have the postalcode.  Oddly enough, my home address does have postalcode listed, but will only come up as a result if the postalcode or city is omitted from the search.  

My guess is these are two different things.  

First being that zipcodes aren't being computed for some streets that were previously.  In placex there were only 1,057 records missing postcodes in my db, so this may be a rare situation.

Second being that leaving out postcode, or city, allows a partial search on street address that isn't done when city and post are included.  I think it may be preferable to search for partial street matches with correct city/postcode, instead of returning no matches or matches with same street but incorrect city/postcode.  I'm not sure if this was changed in the match logic, or something else.

If there's any more information I can help with let me know!

**Comment by lonvia** [comment] 2020-10-05 15:53
You are right that the regression is due to the fact that there is more data but not quite in the way that you think.

If you look at the [debug output for a query](https://nominatim.openstreetmap.org/search.php?street=iron%20stone&city=san%20antonio&county=TX&country=US&postalcode=78230&polygon_geojson=1&format=jsonv2&debug=1) you find somewhere in the middle a table _Search candidates_. This is the table of all possible 'interpretations' of your search query that Nominatim could make. Nominatim goes through them one by one until the database returns a result. For performance reasons it does not go through all the entries but at some point just gives up. You can see which ones are processed in the sections below the table.

Now a couple of things happen for your query: 1) The interpretations that interest you are partial searches and they always come at the end of the table. Perfect matches are preferred. 2) Because there is more data, there are more names in the database, so Nominatim finds more interpretations. The table has become longer over time. As a result, partial queries are less and less likely to be considered. 3) We have added special handling for postcodes, exactly so that they can be ignored when they are missing or differ. Unfortunately that again has added more interpretations to the table, again pushing your partial results down the table. 4) The moment you remove any term (city or postcode or county) from your query, the interpretation table becomes smaller, meaning that Nominatim gets to the end again where the partial searches are. That makes you (wrongly) thing that postcode/city/county is at fault even though everything is fine with them. That part is especially evil.

That's all just to say: geocoding is tricky. ;)

Looking at your particular results, I observe two things:

1) There are searches for postcodes in that interpretations table. That should not happen in a structured search that contains a `street` field. I suspect that fixing this bug already fixes most of your partial searches.
2) We need to increase the number of searches that Nominatim tries.

If you like you can comment out the following line in the code on your server:
* https://github.com/osm-search/Nominatim/blob/f8a5f2964fb4fdcaa774f1149dc6007012af3a2a/lib/Geocode.php#L773
* https://github.com/osm-search/Nominatim/blob/f8a5f2964fb4fdcaa774f1149dc6007012af3a2a/lib/Geocode.php#L845
* https://github.com/osm-search/Nominatim/blob/f8a5f2964fb4fdcaa774f1149dc6007012af3a2a/lib/Geocode.php#L846
This would disable completely the early breakout and ensure that Nominatim always computes the entire table of interpretations. If might make queries a bit slower at times but I doubt that it is noticeable.

**Closed** 2020-10-06 15:04 UTC
