### ISSUE TITLE
Postgres slowed down after daily updates

### ISSUE THREAD

**Issue by rcarroll0452** [osm-search/Nominatim#2642] opened 2022-03-21 12:28 UTC
Since March 12th, I noticed postgres perfomining significantly slow in few of the nominatim servers. (At this exact time, daily updates was completing its run INDEXING at rank 30)

While debugging I found the below query made from nominatim Reverse API is taking significantly huge time by Postgres to respond.
```
select place_id,parent_place_id,rank_address,country_code, ST_distance(ST_SetSRID(ST_Point(-73.98722,40.74807),4326), geometry) as distance FROM placex WHERE ST_DWithin(ST_SetSRID(ST_Point(-73.98722,40.74807),4326), geometry, 0.006) AND rank_address between 26 and 30 and (name is not null or housenumber is not null or rank_address between 26 and 27) and (rank_address between 26 and 27 or ST_GeometryType(geometry) != 'ST_LineString') and class not in ('boundary') and indexed_status = 0 and linked_place_id is null and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon') OR ST_DWithin(ST_SetSRID(ST_Point(-73.98722,40.74807),4326), centroid, 0.006)) ORDER BY distance ASC limit 1
```

 Here's the output for `EXPLAIN ANALYZE` of the above query
```
 Limit  (cost=502835.47..502835.47 rows=1 width=29) (actual time=425.814..425.816 rows=1 loops=1)
   ->  Sort  (cost=502835.47..502885.29 rows=19928 width=29) (actual time=17.717..17.718 rows=1 loops=1)
         Sort Key: (st_distance('0101000020E6100000417DCB9C2E7F52C0328FFCC1C05F4440'::geometry, geometry))
         Sort Method: top-N heapsort  Memory: 25kB
         ->  Index Scan using idx_placex_geometry on placex  (cost=0.80..502735.83 rows=19928 width=29) (actual time=0.544..17.043 rows=2738 loops=1)
               Index Cond: (geometry && st_expand('0101000020E6100000417DCB9C2E7F52C0328FFCC1C05F4440'::geometry, '0.006'::double precision))
               Filter: ((linked_place_id IS NULL) AND (rank_address >= 26) AND (rank_address <= 30) AND (class <> 'boundary'::text) AND (indexed_status = 0) AND ((name IS NOT NULL) OR (housenumber IS NOT NULL) OR ((rank_address >= 26) AND (rank_address <= 27))) AND (((rank_address >= 26) AND (rank_address <= 27)) OR (st_geometrytype(geometry) <> 'ST_LineString'::text)) AND st_dwithin('0101000020E6100000417DCB9C2E7F52C0328FFCC1C05F4440'::geometry, geometry, '0.006'::double precision) AND ((st_geometrytype(geometry) <> ALL ('{ST_Polygon,ST_MultiPolygon}'::text[])) OR st_dwithin('0101000020E6100000417DCB9C2E7F52C0328FFCC1C05F4440'::geometry, centroid, '0.006'::double precision)))
               Rows Removed by Filter: 1260
 Planning Time: 21.153 ms
 JIT:
   Functions: 8
   Options: Inlining true, Optimization true, Expressions true, Deforming true
   Timing: Generation 3.574 ms, Inlining 91.606 ms, Optimization 224.009 ms, Emission 92.083 ms, Total 411.273 ms
 Execution Time: 471.333 ms
(14 rows)
```

Normally this query performs at less than 50ms on the servers. As this issue happened in more servers across different data centers, I suspect the issue could be with the updates? 

I also tried doing `VACUUM ANALYZE placex;` but no improvement in speed. Anything else I could try and check for improvement here? 

**Software Environment:**
- Nominatim version: 3.7.1
- Postgresql version: 12.7
- Postgis version:  POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="6.3.1" LIBXML="2.9.4" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)"
- OS: Ubuntu 20.04.2 LTS

**Hardware Configuration:**
- RAM: 128GB
- number of CPUs: 16cores/32threads
- type and size of disks: 1.9TB SSD
- bare metal/AWS/other cloud service: no cloud services used. All installations are within the same server

**Comment by lonvia** [comment] 2022-03-21 12:43
Duplicate of #2557. Disable JIT and parallel processing:

```
max_parallel_workers_per_gather = 0
jit = off
```

**Closed** 2022-03-22 15:31 UTC
