### ISSUE TITLE
Issue with 180th meridian and bbox for Fiji, Russia, and New Zealand

### ISSUE THREAD

**Issue by burleight** [osm-search/Nominatim#3522] opened 2024-08-22 00:20 UTC
## What did you search for?

This issue seems to apply to 'Fiji', 'Russia', 'New Zealand' and possibly any other results where the geometry intersects the 180th meridian.

## What result did you get?

The `boundingbox` returned for Fiji is `[ "-21.9434274", "-12.2613866", "-180.0000000", "180.0000000" ]` and the `boundingbox` for returned for Russia is `["41.1850968",  "82.0586232", "-180.0000000", "180.0000000"]`

https://nominatim.openstreetmap.org/search.php?q=Russia&polygon_geojson=0&format=jsonv2
https://nominatim.openstreetmap.org/search.php?q=Fiji&polygon_geojson=0&format=jsonv2

New Zealand is similar with boundingbox `[ "-52.8213687", "-29.0303303", "-179.0591530", "179.3643594" ]`

This is a common edge case where using minX and maxX for the bounding box calculation fails to produce a useful result.

I'm happy to look into this if there is appetite to fix this issue.

**Comment by lonvia** [comment] 2024-08-22 07:04
Duplicate of #184.

Yes, it's an old ticket but so far nobody has come up with a good solution to the problem.

**Closed by lonvia** 2024-08-22 07:04 UTC
