### ISSUE TITLE
More flexibility on articles

### ISSUE THREAD

**Issue by sylvain-m** [osm-search/Nominatim#3269] opened 2023-12-08 13:39 UTC
## What did you search for?

I was seaching for a pond mainly named "Étang **du** Chédouet"
In OSM, this pond was named "Étang **de** Chédouet".
Both names are used locally.

OSM relation link : https://www.openstreetmap.org/relation/14220732
(I've renamed it after this search, and addedd an `alt_name`)

## What result did you get?
I got no results :
![image](https://github.com/osm-search/Nominatim/assets/11629210/12c6d87a-6541-4520-8c04-83d9a3876cda)

## What result did you expect?

I would have liked the searches to have been more flexible and more tolerant of articles.
I imagine that it's technically complicated, but I have to admit that I very often end up with searches with no results, just because of a few characters difference.

Following the example of a famous proprietary search engine, it would be nice to add suggestions to the results based on places with 'almost the same name'. This would be particularly useful on the main OSM page (https://www.openstreetmap.org), which is a showcase for this project.

**Comment by lonvia** [comment] 2023-12-18 15:03
Duplicate of #753.

**Closed by lonvia** 2023-12-18 15:03 UTC
