### ISSUE TITLE
Administrative boundary should be loosened to include ETJ's or we should utilize OMB's statistical zones.

### ISSUE THREAD

**Issue by EvanCarroll** [osm-search/Nominatim#2943] opened 2023-01-10 20:31 UTC
City of Houston be visualized here,

https://www.openstreetmap.org/relation/2688911#map=11/29.8078/-95.3209

This is an import from US Census Bureau which includes just the city's outline. However, that's not useful because of the American concept of an [Extraterritorial jurisdiction](https://en.wikipedia.org/wiki/Extraterritorial_jurisdiction). This means, on the ground, we call things that are outside of the city proper still a part of the city, and they receive services from the city and even get a city-address with USPS. This is confusing because trying to find a pet shop, one may query for `pet shop in houston` and [get a query like this](https://www.openstreetmap.org/search?query=pet%20shop%20in%20houston#map=19/29.77404/-95.38318). But this will lack [S & S Exotic Animals](https://www.openstreetmap.org/way/943430365), which is very much in Houston too and they even advertise that they're in Houston. There are two ways this can be solved,

* Providing an interface to OMB's statistical areas, and mapping "Houston" to ["Greater Houston"](https://en.wikipedia.org/wiki/Greater_Houston), and a general `Foo` to `Greater Foo` when it exists. This can be integrated into the "More results"  button when the choices are exhausted.
* Importing the ETJ files in addition to the city-files so we have another administrative boundary that holds a higher precedent for the purposes of querying.

[USPS lookup](https://tools.usps.com/zip-code-lookup.htm?byaddress) for S & S Exotic Animals
------

Notice the address shows "Houston"

![Screenshot_2023-01-10_14-34-23](https://user-images.githubusercontent.com/19922/211656271-9e76efa6-b0f2-4276-951f-d3b30f3fdd74.png)

**Comment by mtmail** [comment] 2023-01-10 21:56
The official boundaries of Las Vegas (https://www.openstreetmap.org/relation/170117) are even more head scratching.

Both your suggestions require somebody to add new data to OpenStreetMap (there is no place called Greater Houston in OSM yet). Or maybe even remove those official boundaries or tag them differently and replace them with other boundaries. ETJ files looks like an interesting find, pending data licence compatibilty of course. That's outside the scope of Nominatim's issue tracker though. Better to discuss with the local OpenStreetMap US chapter (https://openstreetmap.community/ , https://lists.openstreetmap.org/listinfo/talk-us) first.

**Comment by EvanCarroll** [comment] 2023-01-10 21:57
That's a great suggestion, and I'll take it there.

**Comment by lonvia** [comment] 2023-01-14 08:51
Duplicate of #1120.

**Closed by lonvia** 2023-01-14 08:51 UTC
Labels: duplicate
