### ISSUE TITLE
strange results with hamlets (and maybe other small node places like isolated_dwelling)

### ISSUE THREAD

**Issue by Megachip** [osm-search/Nominatim#1820] opened 2020-06-02 21:32 UTC
Nominatim put all these following coordinates zu `Finkenherd`. 
![image](https://user-images.githubusercontent.com/487352/83571869-e192f180-a528-11ea-9c76-3f811ffa9b89.png)
At the end, only one is correct:
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.211814&lon=13.443146&zoom=42&accept-language=en&addressdetails=1
All others are not even nearby.
Just two examples:
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.235369&lon=13.445892&zoom=42&accept-language=en&addressdetails=1
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.218546&lon=13.473358&zoom=42&accept-language=en&addressdetails=1

Any chance to (fine) tune it, to prevent such wrong results? Seen such things much more often :(

**Comment by mtmail** [comment] 2020-06-02 21:35
Please add the full search URL you used. A screenshot of the result can help. When I search I don't see any black dots.

**Comment by Megachip** [comment] 2020-06-02 21:49
> Please add the full search URL you used. A screenshot of the result can help. When I search I don't see any black dots.

Thats a screenshot from our internal tool, which visualize the result of multiple nominatim requests.
Not sure about feeding nominatim directly with an list of coordinates.  

I can give you a list of there 19 coordinates, if this would help ... maybe extending later with other regions, where we monitor such a behavior?

**Comment by mtmail** [comment] 2020-06-02 21:56
You need to provide us a way to reproduce the issue you see: specific Nominatim URLs you called, which results you saw, what the expected results are. If it's multiple requests, then list multiple. The less we have guess, the better.

**Comment by lonvia** [comment] 2020-06-03 06:15
Basically the same as you reported in #813 already?

**Comment by Megachip** [comment] 2020-06-03 16:51
> Basically the same as you reported in #813 already?

Looks like that. Read the FAQ. But ill guess there are other place nodes much nearer like that:
https://www.openstreetmap.org/node/240095909




> You need to provide us a way to reproduce the issue you see: specific Nominatim URLs you called, which results you saw, what the expected results are. If it's multiple requests, then list multiple. The less we have guess, the better.

will provide you the rest of the links asap. 3 You already see in the issue, the one, which is correct and the two most far away 

So, normally I'll guess a hamlet or isolated_dwelling is really really small ... so maybe coordinates which are kilometres away shouldn't be assigned to that place?

**Comment by lonvia** [comment] 2020-06-05 15:17
Zossen is a place=town, not a place=hamlet. With the mapping as is Finkenherd could be a suburb of Zossen.

Closing as duplicate of #813.

**Closed by lonvia** 2020-06-05 15:17 UTC

**Comment by Megachip** [comment] 2020-06-07 11:40
> will provide you the rest of the links asap. 3 You already see in the issue, the one, which is correct and the two most far away
http://nominatim.openstreetmap.org/reverse?format=json&lat=52.235369&lon=13.445892&zoom=42&accept-language=en&addressdetails=1
http://nominatim.openstreetmap.org/reverse?format=json&lat=52.233687&lon=13.445892&zoom=42&accept-language=en&addressdetails=1
http://nominatim.openstreetmap.org/reverse?format=json&lat=52.232005&lon=13.445892&zoom=42&accept-language=en&addressdetails=1
http://nominatim.openstreetmap.org/reverse?format=json&lat=52.230323&lon=13.445892&zoom=42&accept-language=en&addressdetails=1
http://nominatim.openstreetmap.org/reverse?format=json&lat=52.228641&lon=13.443146&zoom=42&accept-language=en&addressdetails=1
http://nominatim.openstreetmap.org/reverse?format=json&lat=52.228641&lon=13.445892&zoom=42&accept-language=en&addressdetails=1
http://nominatim.openstreetmap.org/reverse?format=json&lat=52.226958&lon=13.443146&zoom=42&accept-language=en&addressdetails=1
Did it really helps you, if I post all 31 links here?


> Zossen is a place=town, not a place=hamlet. With the mapping as is Finkenherd could be a suburb of Zossen.

Thats right, Finkenherd is a small hamlet within zossen https://www.openstreetmap.org/node/447087591

But the issue here is, that Ill guess, no navigation software would find all the streets (and housenumbers) within finkenherd. Cause it just has one street with about 20 numbers... 

There is no `"road":"Herrmann-Bohnstedt-Straße","hamlet":"Finkenherd"` or `"road":"Luchweg","hamlet":"Finkenherd"` ...

**Comment by mtmail** [comment] 2020-06-07 20:18
I can't find a secondary source for Finkenherd, not even on the city's website. Satellite imagery suggest a couple of houses, Mapillary (like Google Street View, but open) doesn't show any street signs or other markers. https://www.mapillary.com/app/?lat=52.21317686138886&lng=13.444792628055552&z=16&focus=photo&pKey=ZV4UrAnU5KOuqjRx_n3G5Q

Over the years the same mapper added several `place=locality` nearby: 'Die faule See', 'Am Laufgraben', 'Johne', 'Wulzenplan'. I'm guessing Finkenherd was an old name for a farm or family name that once existed, something people living there might still understand as location, but not something people use in official or postal addresses. It was mapped 11 years ago. The building, address nodes and most other features around it were added 5, some 10 years later.

**Comment by Megachip** [comment] 2020-06-07 21:02
I'll guess we would find millions of these stuff... 
Maybe you should just integrated `hamlet` into the results, if the node is less than 100 m or 200 m away from the result.

Another example: 
https://www.openstreetmap.org/relation/1080467
https://www.openstreetmap.org/node/256481359

https://nominatim.openstreetmap.org/reverse?format=json&lat=49.741344&lon=11.056366&zoom=42&accept-language=en&addressdetails=1
https://nominatim.openstreetmap.org/reverse?format=json&lat=49.680958&lon=11.053619&zoom=42&accept-language=en&addressdetails=1

These coordinates are kilometers away from `Sigritzau`, so why integrate this into the result? Nobody will find the `A 73` or `Eggolsheimer Weg` within this hamlet.

**Comment by Megachip** [comment] 2020-06-12 22:27
http://nominatim.openstreetmap.org/reverse?format=json&lat=58.548911&lon=15.060883&zoom=42&accept-language=en&addressdetails=1
http://nominatim.openstreetmap.org/reverse?format=json&lat=58.550344&lon=15.063629&zoom=42&accept-language=en&addressdetails=1

`"residential":"Motala Verkstad"` is correct:
https://www.openstreetmap.org/way/161220093
`"hamlet":"Sättran"` definitively not:
https://www.openstreetmap.org/node/7465223342

I would be really happy about feedback. Any plans to fix this or will this stay as it is?

**Comment by Megachip** [comment] 2020-06-14 08:30
Example Mönninghausen (small hamlet with 3 houses):
![image](https://user-images.githubusercontent.com/487352/84588670-d6459d00-ae29-11ea-9ef3-f6c4ef1e57e0.png)
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.149501&lon=13.368988&zoom=42&accept-language=en&addressdetails=1
https://nominatim.openstreetmap.org/reverse?format=json&lat=52.144445&lon=13.358002&zoom=42&accept-language=en&addressdetails=1
