### ISSUE TITLE
Use a UK postcode and cannot find it in map

### ISSUE THREAD

**Issue by PungoIssue** [osm-search/Nominatim#2020] opened 2020-10-20 15:36 UTC
I have used DN38 6BN and no resulst are given. Using Google produces the correct result.
![Google results with a postcode](https://user-images.githubusercontent.com/73185692/96609307-4b524300-12f2-11eb-916d-55b6f0122a61.JPG)
![Nominatim result for a postcode search](https://user-images.githubusercontent.com/73185692/96609313-4c837000-12f2-11eb-9e97-f697910d858e.JPG)

**Comment by mtmail** [comment] 2020-10-20 15:39
Royalmail doesn't know the postcode either https://www.royalmail.com/find-a-postcode so I would argue it doesn't exist. I can't find it in old historical lists either.

**Comment by mtmail** [comment] 2020-10-20 15:42
Google Maps is displaying the center of DN38 postcode district. We track the feature to shorten the postcode in https://github.com/osm-search/Nominatim/issues/1011

**Comment by lonvia** [comment] 2020-10-22 07:42
Closing as duplicate.

**Closed by lonvia** 2020-10-22 07:42 UTC

**Comment by PungoIssue** [comment] 2020-10-22 08:42
Hi there, I tried the royal mail search and enter the full postcode DN38 6BN and the address is found.
 
![royal mail does find the address](https://user-images.githubusercontent.com/73185692/96846675-1fe26c00-144a-11eb-928d-fb4f217bcdea.jpg)

**Comment by PungoIssue** [comment] 2020-10-22 13:42
> 
> 
> Royalmail doesn't know the postcode either https://www.royalmail.com/find-a-postcode so I would argue it doesn't exist. I can't find it in old historical lists either.

I am able to find the address when royalmail, I enter the full postcode. See attached screenshot.
![royal mail does find the address](https://user-images.githubusercontent.com/73185692/96880183-cba0b180-1474-11eb-994c-7a625b2d1b32.jpg)

**Comment by lonvia** [comment] 2020-10-22 14:50
It's still a data issue, not a bug in Nominatim. Nominatim finds what is in OpenStreetMap. If the postcode is not mapped there, Nominatim can't show it.
