### ISSUE TITLE
Second search with looser criteria if 0 results from the query

### ISSUE THREAD

**Issue by dieterdreist** [osm-search/Nominatim#2849] opened 2022-10-29 22:52 UTC
Getting 0 results can be frustrating. Maybe Nominatim could try a second time with less strict criteria whether there could be matches that were missed in the stricter search?

For example a common error is people confusing similar street types, in particular the street is called "viale" and they search for "via" or the other way round, maybe also "vicolo". While these are not synonymous, and direct hits are clearly preferable, it would be better to show such matches than nothing.

**Comment by lonvia** [comment] 2022-10-30 08:42
Duplicate of #145 and a couple of other open tickets that request fuzzy search for Nominatim.

I'm quite aware that this much requested feature but it also happens to be one of the most difficult feature to implement. 'Looser criteria' is the equivalent of asking to add magic. It's not really something actionable.

**Closed by lonvia** 2022-10-30 08:42 UTC
Labels: duplicate
