### ISSUE TITLE
Differences 3.6.0 vs 3.5.1

### ISSUE THREAD

**Issue by RailsGuy** [osm-search/Nominatim#2126] opened 2021-01-05 10:56 UTC
Hi there I run tests against my nominatim server and noticed differences after moving to 3.6.0. Here is one example which is correct on 3.5.1 but not found on 3.6.0. Can you explain it?

## What did you search for?
suttons park avenue, reading, united kingdom

https://nominatim.openstreetmap.org/ui/search.html?q=suttons+park+avenue%2C+reading%2C+united+kingdom&dedupe=0

## What result did you get?
No search results found

## What result did you expect?

With Nominatim 3.5.1 I see this result which is correct

Name | Suttons Park Avenue (name)
-- | --
Type | highway:unclassified
Last Updated | Sat, 24 Oct 20 11:14:47 +0000
Admin Level | 15
Rank | street / major landmark
Importance | 0.1 (estimated)
Coverage | Point
Centre Point | 51.45761,-0.9354938
OSM | way 379458728
Place Id (on this server) | 297377028
Computed Postcode | RG6 1AW
Address Tags |  
Extra Tags | 30 mph (maxspeed)asphalt (surface)

Local name | Type | OSM | Address rank | Admin level | Distance |  
-- | -- | -- | -- | -- | -- | --
Suttons Park Avenue | highway:unclassified | way 379458728 | 26 |   | 0 | details >
Suttons Business Park | landuse:industrial | way 3113900 | 22 |   | 0.0022 | details >
Earley | boundary:administrative(suburb) | relation 3884427 | 20 | 10 | 0.0237 | details >
Newtown | place:suburb | node 6399615991 | 20 |   | 0.011 | details >
Sonning | place:village | node 558816949 | 16 |   | 0.0302 | details >
Reading | place:town | node 14808039 | 16 |   | 0.0319 | details >
Playhatch | place:hamlet | node 2254658315 | 16 |   | 0.0217 | details >
Sonning Eye | place:hamlet | node 2255655933 | 16 |   | 0.026 | details >
Wokingham | boundary:administrative | relation 114311 | 12 | 6 | 0.0589 | details >
South East | boundary:administrative | relation 151304 | 10 | 5 | 0.447 | details >
England | boundary:administrative | relation 58447 | 8 | 4 | 1.1811 | details >
RG6 1AW | place:postcode |   | 5 |   | 0 |  
Royaume-Uni | place:country |   | 4 |   | 0 |  
gb | place:country_code |   | 4 |   | 0

Suttons Park Avenue 

https://nominatim.openstreetmap.org/ui/search.html?q=suttons+park+avenue&dedupe=0

**Comment by mtmail** [comment] 2021-01-05 11:07
I looks like the road https://www.openstreetmap.org/way/2978523 is indeed in town Earley https://www.openstreetmap.org/relation/3884427 not Reading https://www.openstreetmap.org/relation/115074 Town/parishes in England are a challenge but Earley and Reading boundaries seem mutually exclusive.

**Comment by mtmail** [comment] 2021-01-05 11:17
"Reading's municipal boundaries do not include all of the surrounding suburbs which contain a third of Reading's population. Some of these areas (Tilehurst, Calcot, Earley, Winnersh and Woodley) are, at least partly, within West Berkshire or Wokingham Borough. This unusual configuration creates difficulties." https://en.wikipedia.org/wiki/en:Reading,%20Berkshire?uselang=en-GB

**Comment by SomeoneElseOSM** [comment] 2021-01-05 11:46
It's not the only UK example - [Nottingham](https://www.openstreetmap.org/relation/123292) is similar.  

It's not the only way that what nominatim returns doesn't match people's expectations - [here](https://help.openstreetmap.org/questions/78135/nodes-relations-and-zoom-levels) on the help site is another.  For the avoidance of doubt, what Nominatim is returning in that example is also correct within its own terms (the local adminsitrative hierarchy) - it is just that, as here, it does not match what the person searching expects to get back.

**Comment by lonvia** [comment] 2021-01-05 13:47
Nominatim returns what is being mapped in OSM. It can't make up things that aren't there. I've looked a bit into how boundaries and places are mapped in the UK and I'm afraid it is not possible to make something useful for geocoding out of it. If you like to have better results, the UK community needs to sit together and come up with a tagging schema that is somehow usable across the country. Nominatim can ignore admin boundaries and use other areas instead. That's not really the issue. The issue is that every time I ask a local about this or that place in the UK, the answer is usually: "oh, that is a bit special" and that's not something Nominatim can derive rules from.

**Comment by RailsGuy** [comment] 2021-01-06 11:00
Thank you I was also interested to understand what changed. On v 3.5.1 I see "Reading | place:town" (greyed out) in the address details for "Suttons Park Avenue" but this is not present on the later version. I don't think the OSM data has changed recently so is this due to 'Administrative boundaries' changes in Nominatim https://github.com/osm-search/Nominatim/releases/tag/v3.6.0

**Nominatim 3.5.1 - Data last updated: 2020/11/27 03:44 GMT**

Local name | Type | OSM | Address rank | Admin level | Distance |  
Suttons Park Avenue | highway:unclassified | way 379458734 | 26 |   | 0 | details >
Suttons Business Park | landuse:industrial | way 3113900 | 22 |   | 0.0007 | details >
Earley | boundary:administrative(suburb) | relation 3884427 | 20 | 10 | 0.0263 | details >
Newtown | place:suburb | node 6399615991 | 20 |   | 0.0039 | details >
Sonning Eye | place:hamlet | node 2255655933 | 16 |   | 0.0297 | details >
Playhatch | place:hamlet | node 2254658315 | 16 |   | 0.0221 | details >
Reading | place:town | node 14808039 | 16 |   | 0.0244 | details >
Wokingham | boundary:administrative | relation 114311 | 12 | 6 | 0.0633 | details >
South East | boundary:administrative | relation 151304 | 10 | 5 | 0.4517 | details >
England | boundary:administrative | relation 58447 | 8 | 4 | 1.1762 | details >
RG6 1AA | place:postcode |   | 5 |   | 0 |  
Royaume-Uni | place:country |   | 4 |   | 0 |  
gb | place:country_code |   | 4 |   | 0

**nominatim.openstreetmap.org**

Local name | Type | OSM | Address rank | Admin level | Distance |  
-- | -- | -- | -- | -- | -- | --
Suttons Park Avenue | highway:unclassified | way 379458727 | 26 |   | 0 | details
Suttons Business Park | landuse:industrial | way 3113900 | 22 |   | ~0.001 | details
Earley | boundary:administrative (suburb) | relation 3884427 | 20 | 10 | ~0.021 | details
Wokingham | boundary:administrative | relation 114311 | 12 | 6 | ~0.054 | details
South East | boundary:administrative | relation 151304 | 10 | 5 | ~0.053 | details
England | boundary:administrative (state) | relation 58447 | 8 | 4 | ~1.122 | details
RG6 1AZ | place:postcode |   | 5 |   | 0 |  
United Kingdom | place:country |   | 4 |   | 0 |  
gb | place:country_code

**Comment by lonvia** [comment] 2021-01-11 10:28
3.6.0 has significantly reduced the influence of place nodes because they mostly caused results to be degraded.

I'm going to close this as a data issue because there really isn't anything actionable in terms of coding at the moment. If you want to pursue this further, I recommend opening a thread under 'discussion' about what OSM data to use in the UK to determine addresses/location descriptions. I've added a new category 'Geocoding around the world' for it.

**Closed by lonvia** 2021-01-11 10:28 UTC
