### ISSUE TITLE
Wong Post Code In Venice

### ISSUE THREAD

**Issue by dimalif** [osm-search/Nominatim#3203] opened 2023-09-19 12:43 UTC
## What did you search for?

https://www.openstreetmap.org/search?query=Palazzo%20Grassi%2C%20venice#map=19/45.43377/12.32794

## What result did you get?

Museum [Palazzo Grassi, Calle Grassi, San Marco, Venezia-Murano-Burano, Venice, Venezia, Veneto, 30170, Italy](https://www.openstreetmap.org/way/173619525)

The post code is wrong, 30170 is MESTRE. 

## What result did you expect?

Post Code 30124

## Further details

This is an old issue that i reported here:

https://github.com/osm-search/Nominatim/issues/3142

and was closed. THAT issue somehow was fixed, BUT now the same problem appeared in other areas of Venice (San Marco district).

**Comment by otbutz** [comment] 2023-09-19 12:51
> As with the other, I'm closing in favour of https://github.com/osm-search/Nominatim/issues/2606 which discusses a possible solution to the problem.

https://github.com/osm-search/Nominatim/issues/3142#issuecomment-1699781436

**Comment by lonvia** [comment] 2023-09-19 21:21
Duplicate of #3142.

**Closed by lonvia** 2023-09-19 21:21 UTC

**Comment by dimalif** [comment] 2023-09-19 21:33
Closed as completed? what does that mean? Please be more clear for all of us that have no idea about all that.

**Comment by otbutz** [comment] 2023-09-20 07:55
@dimalif your problem has the same root cause as #2606. You can follow that issue to be notified once a solution is found.
