### ISSUE TITLE
Outdated polygons on countries compared to OSM data

### ISSUE THREAD

**Issue by eseglem** [osm-search/Nominatim#2831] opened 2022-09-27 22:08 UTC
## What did you search for?
Syria

## What result did you get?
Syria with an outdated Polygon that does not reflect the current data in OSM.

## What result did you expect?
Syria with the current Polygon.

## Further details

If you view [Syria](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=184840&class=boundary) and go to the NE corner of Lebanon, you can see where it cuts across sections of Lebanon and does not align with the boundary seen in the background tiles. The [Lebanon](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=184843&class=boundary) polygon however lines up with the background map.
Search with view box: [Here](https://nominatim.openstreetmap.org/ui/search.html?q=Syria&viewbox=36.34637,34.67147,36.50086,34.53215)

[Azerbaijan](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=364110&class=boundary) overlaps a part of [Armenia](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=364066&class=boundary) 
Search with view box: [Here](https://nominatim.openstreetmap.org/ui/search.html?q=Azerbijan&viewbox=45.56923,40.02913,45.64648,39.96430)

There many additional small areas around the world where the topologies have changed but don't seem to be reflected in both countries, rather they are only up to date in one of them. I wonder if things aren't quite being rebuilt correctly when a large relation is updated? It always one updated and one not. Below are a handful of examples I have found. 

| old | new|
|-|-|
| Syria| Lebanon |
| Azerbaijan | Armenia |
| Mongolia | China |
| Armenia | Georgia |
| Nigeria | Cameroon |
| Kazakhstan | Uzbekistan |
| Ecuador | Columbia |
| South Africa | Botswana, Mozambique |

**Comment by mtmail** [comment] 2022-09-27 22:44
Screenshot from nominatim.osm.org ![image](https://user-images.githubusercontent.com/3727288/192650456-8874c720-150b-42da-b4c5-b58555d34889.png)

I don't see the those border differences in a fresh install on my computer so it could indeed be outdated data (and not polygon simplification)

**Comment by lonvia** [comment] 2022-09-28 07:09
Relation geometries are not updated when nodes are moved around. This was a conscious decision due to performance reasons. Small changes like this don't usually have an effect on the search results, so it is mostly cosmetic.

Closing as duplicate of #2563.

**Closed by lonvia** 2022-09-28 07:09 UTC

**Comment by eseglem** [comment] 2022-09-28 12:24
@lonvia I may have focused on the wrong part of the issue in my report. My main problem is not necessarily that polygons are outdated. Its that the topologies in the results are off. If the polygons all matched, then I would never have noticed. If Syria and Lebanon were both outdated, totally understandable. But Syria **is** outdated and Lebanon **is not** outdated. So it appears that somewhere along the line the Lebanon relation was actually updated, but the Syria one was not. 

![boundaries](https://user-images.githubusercontent.com/5920492/192774675-558d392a-1477-4dce-92e0-bb7b9d534f0e.jpg)

Its not the greatest snapshot but the green areas are overlapped and blue are gaps.

Is it something along the lines of the polygons are updated when the relation itself is updated? Lebanon relation was last updated Sep 10, and the Syria relation was last updated on July 18. So if the edit happened in that time Lebanon received it, but Syria relation hasn't been updated and doesn't receive it?

**Comment by lonvia** [comment] 2022-09-28 13:15
> Is it something along the lines of the polygons are updated when the relation itself is updated? Lebanon relation was last updated Sep 10, and the Syria relation was last updated on July 18. So if the edit happened in that time Lebanon received it, but Syria relation hasn't been updated and doesn't receive it?

Yes. And this inconsistency still doesn't greatly impede Nominatim's main function of being a geocoder. There are much worse ones.
