### ISSUE TITLE
Nominatim compile fails with -DBUILD_OSM2PGSQL=off 

### ISSUE THREAD

**Issue by di-rect** [osm-search/Nominatim#2193] opened 2021-03-02 16:15 UTC
**Describe the bug**
When building Nominatim without the osm2pgsql module the build fails when set to `on` no problem there.

**To Reproduce**

```
git clone --config advice.detachedHead=false --depth 1 --branch ${nominatim_version} --single-branch --recursive https://github.com/osm-search/Nominatim.git \
mkdir build \
cd build \
cmake -DBUILD_OSM2PGSQL=off ../Nominatim \
make -j5 \
```

```
Cloning into 'Nominatim'...
Submodule 'osm2pgsql' (https://github.com/openstreetmap/osm2pgsql.git) registered for path 'osm2pgsql'
Cloning into '/opt/src/Nominatim/osm2pgsql'...
Submodule path 'osm2pgsql': checked out 'a65ab49f777b9785726117971d3a4140436d70aa'
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.7", minimum required is "3")
CMake Warning at CMakeLists.txt:69 (message):
  pyosmium-get-changes not found (required for updates)


-- Using PHP binary /usr/bin/php
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/src/build
Scanning dependencies of target nominatim_lib
[100%] Running external makefile /usr/lib/postgresql/pgxs/src/makefiles/pgxs.mk
/opt/src/Nominatim/module/Makefile:11: warning: overriding recipe for target 'install'
/usr/lib/postgresql/pgxs/src/makefiles/pgxs.mk:241: warning: ignoring old recipe for target 'install'
[100%] Built target nominatim_lib
make: *** No rule to make target 'install'.  Stop.
```

I have the feeling that the existence of PHP install is also involved which should not for building only.

**Software Environment (please complete the following information):**
- Nominatim version: v3.6.0
- Postgresql version: 13.2-r0
- Postgis version: none
- OS: Alpine

**Comment by lonvia** [comment] 2021-03-02 16:37
I cannot reproduce that, neither on 3.6.0 nor on master.

The error is a bit odd anyway. `*** No rule to make target 'install'.` indicates that you actually have tried a `make install`. And that wouldn't work with 3.6.0. Support for `make install` has only arrived a week ago on master.

**Comment by di-rect** [comment] 2021-03-02 16:42
> I cannot reproduce that, neither on 3.6.0 nor on master.
> 
> The error is a bit odd anyway. `*** No rule to make target 'install'.` indicates that you actually have tried a `make install`. And that wouldn't work with 3.6.0. Support for `make install` has only arrived a week ago on master.

Ah that explains a lot! I was also seeing differences between the Git .md and Docs. Maybe some small additional lines about this are an idea there ?

**Comment by lonvia** [comment] 2021-03-02 16:46
I take it that this is a false alarm then. Closing.

**Closed by lonvia** 2021-03-02 16:46 UTC

**Comment by di-rect** [comment] 2021-03-02 18:44
> I take it that this is a false alarm then. Closing.

Yes fair enough! Thanks!
