### ISSUE TITLE
Search does not work correctly

### ISSUE THREAD

**Issue by djin1989** [osm-search/Nominatim#2097] opened 2020-12-09 09:25 UTC
Hello! I am using api for my site. When I try to find a building at "Железнодорожная 44 Минск", it gives me only streets and bus stops, but the house was not found. I checked this through https://nominatim.openstreetmap.org/ui/search.html?q=%D0%96%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BD%D0%B0%D1%8F%2044%20%D0%BC%D0%B8%D0%BD%D1%81%D0%BA - the same (https://nominatim.openstreetmap.org/search.php?q=%D0%96%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BD%D0%B0%D1%8F%2044%20%D0%BC%D0%B8%D0%BD%D1%81%D0%BA&polygon_geojson=1&format=jsonv2), but after clicking the "show more results" button, only 1 result remained (https://nominatim.openstreetmap.org/search.php?q=%D0%96%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BD%D0%B0%D1%8F%2044%20%D0%BC%D0%B8%D0%BD%D1%81%D0%BA&polygon_geojson=1&exclude_place_ids=59386694%2C1311109%2C43115408%2C20188095&format=jsonv2) again, I got the desired result with the house and the establishments that are in it (https://nominatim.openstreetmap.org/search.php?q=%D0%96%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D0%BD%D0%B0%D1%8F%2044%20%D0%BC%D0%B8%D0%BD%D1%81%D0%BA&polygon_geojson=1&exclude_place_ids=59386694%2C1311109%2C43115408%2C2006378095%2C20188095%2C20063773&format=jsonv2), how do I get a normal result right away?

**Comment by lonvia** [comment] 2020-12-09 11:02
Duplicate of #1871 and #1790.

You have to give the full name of the street (Железнодорожная улица) to get the right result right away.

**Closed by lonvia** 2020-12-09 11:02 UTC
