### ISSUE TITLE
Possibility of supporting Chinese language address order?

### ISSUE THREAD

**Issue by c933103** [osm-search/Nominatim#1796] opened 2020-05-14 00:53 UTC
Currently, the address order Nominatim generate and display for Chinese language look like this (using 22.36651N, 114.13703E as example):
雍澄軒酒店, 33, 和宜合道, 石籬, 石梨山村, 新界, 葵青區, 香港, 中国
However, in regular Chinese language expression, the correct address order should be like this:
中国香港新界葵青區石籬石梨山村和宜合道33號雍澄軒酒店
Is there any chance for Nominatim to support such address order from Chinese language?

**Comment by mtmail** [comment] 2020-05-14 01:15
It's a common feature request but currently there's no country specific logic for the address string format yet. Marking as duplicate of https://github.com/osm-search/Nominatim/issues/213

**Closed by mtmail** 2020-05-14 01:15 UTC

**Comment by c933103** [comment] 2020-05-14 06:29
This is language rule not country rule. This address rule applies to all corner of the world.

**Comment by mtmail** [comment] 2020-05-14 11:40
We will update this issue if we made progress in either by-country or by-language.
