### ISSUE TITLE
Reverse search in Finland mixes neighborhoods from different municipalities

### ISSUE THREAD

**Issue by mod3330** [osm-search/Nominatim#3537] opened 2024-09-18 18:24 UTC
## What did you search for?

https://nominatim.openstreetmap.org/ui/reverse.html?lat=60.2092&lon=24.7205&zoom=18

## What result did you get?

15, Ersintie, Ymmersta, 2, Vanha-Espoo, Kauniainen, Helsinki sub-region, Uusimaa, Mainland Finland, 02700, Finland

## What result did you expect?

**When the result in the right place and just named wrongly:** 

15, Ersintie, 2, Kauniainen, Helsinki sub-region, Uusimaa, Mainland Finland, 02700, Finland

## Further details

Address is inside Kauniainen municipality, so it shouldn't contain Ymmersta or its parent Vanha-Espoo. Those are in Espoo, which is another municipality altogether.

In fact the point is not even enclosed by those relations, so it is unclear why they are returned. The same query with zoom level 14 returns the correct neighborhood.

**Comment by lonvia** [comment] 2024-09-19 08:37
That's another issue of roads crossing boundaries. There should be a an open issue about this somewhere.

**Comment by lonvia** [comment] 2024-09-19 08:49
Found it. Closing as duplicate of #2658.

**Closed by lonvia** 2024-09-19 08:49 UTC
