### ISSUE TITLE
Actually incompatible with PostgreSQL 9.4?

### ISSUE THREAD

**Issue by andrec93p** [osm-search/Nominatim#2394] opened 2021-07-16 10:35 UTC
**Describe the bug**

I'm trying to install Nominatim with custom data on a machine with PostgreSQL 9.4, which [should be compatible according to the docs](https://nominatim.org/release-docs/latest/admin/Installation/#prerequisites). The problem is that I'm unable to complete the first import of PBF data because there is a PL/pgSQL function that breaks on this version.

To be precise, we're talking about the function **create_poi_search_terms**, that fails because it tries using **array_agg** with an array as a parameter. Despite the official documentation not being that clear, this is not allowed in PostgreSQL versions prior to 9.5 ([https://www.postgresql.org/docs/9.5/functions-aggregate.html](https://www.postgresql.org/docs/9.5/functions-aggregate.html)).

The subject is a question because this could actually be a problem with my own configuration, but I can't be sure about it. On this machine, I **do** have a version of PostgreSQL 12 set up and running, but I'm quite confident I made sure to set the 9.4 as the system default. In fact, building Nominatim without any specific option or setting correctly installs the module for the 9.4 version. Furthermore, even looking at the code on Github, I can't find any version of the function above that could work on 9.4.

**To Reproduce**

Simply install a new instance of Nominatim 3.7.2 with PostgreSQL 9.4 following the [basic installation guide](https://nominatim.org/release-docs/latest/admin/Installation/), then try importing any PBF file onto it. I'm testing with [a small one](https://download.geofabrik.de/europe/andorra-latest.osm.pbf) to be quicker, but any source is fine.

**Software Environment:**
- Nominatim version: 3.7.2
- Postgresql version: 9.4
- Postgis version: 2.5
- OS: Debian 10.10

**Hardware Configuration:**
- RAM: 32GB
- number of CPUs: 8
- type and size of disks: HDD, 2TB
- bare metal/AWS/other cloud service: Dedicated Hetzner server

**Postgresql Configuration:**

The default one.

**Additional context**

This is most likely a problem of outdated documentation more than a bug or an error, but I'm reporting it here so other people don't lose their time like I did trying to make it work. If this report is not correct or not in the right category, I apologize. Thank you.

**Comment by lonvia** [comment] 2021-07-16 19:22
We can't really test 9.4 anymore, so I would not be surprised if there are issues.

Can you paste the actual array message? The only `array_agg()` I see in `create_poi_search_terms` collects bigints, so this should be fine with 9.4.

**Comment by andrec93p** [comment] 2021-07-19 09:03
I lost the log, but I'll make another import attempt and provide the error message as soon as possible.

By the way, I was talking about the function `create_poi_search_terms ` in `lib-sql/functions/normalization.sql`. Specifically, [this](https://github.com/osm-search/Nominatim/blob/c4fd94bd1a778785e67e28d9e77044c6b09a07ff/lib-sql/functions/normalization.sql#L455) is the query that fails.

``` -- Find all address tags that don't appear in the parent search names.
  SELECT hstore(array_agg(ARRAY[k, v])) INTO filtered_address
    FROM (SELECT skeys(address) as k, svals(address) as v) a
   WHERE not addr_ids_from_name(v) && parent_address_vector
         AND k not in ('country', 'street', 'place', 'postcode',
                       'housenumber', 'streetnumber', 'conscriptionnumber');`

I'll see if I can post the import log later today.

**Comment by lonvia** [comment] 2021-07-19 09:19
I see, thanks. I was looking at master which doesn't have this function anymore.

We'd need to write our own hstore_agg function to work around this. This wouldn't be particularly difficult. I'll do that if there is another minor release of 3.7. So let's leave the issue open for now. (If you urgently need 9.3. compatibility, feel free to provide a patch with an hstore_agg function and I can do a release with it.)

Regarding the upcoming 4.0 release, I've just decided to bump the minimum required version to 9.5. We need this for proper jsonb support anyway.

**Comment by andrec93p** [comment] 2021-07-19 13:37
Thank you, I already set up Nominatim using PostgreSQL 12, so I'm OK.

In case you could still use the error log, I'm sorry but right now I have no easy way to produce it. I'd have to reinstall Nominatim from scratch to get the other version of the database module at this point. The database error, however, is this one, quite obscure as well.
```
ERROR:  could not find array type for data type text[]
SQL state: 42704
```
If I get another chance, I'll post the Nominatim log, that also reported the function in which the error occurred. Shouldn't be anything new compared to what I was already saying above though.

I'm fine with PostgreSQL 9.4 not being supported. [Not even the official development group supports anything below 9.6](https://www.postgresql.org/support/versioning/) at the time of writing, so I see no major problems with that. As I said in the first message, the only thing that I think should be fixed is the documentation, that currently [lists 9.3 as the minimum requirement](https://nominatim.org/release-docs/latest/admin/Installation/#prerequisites).

**Comment by lonvia** [comment] 2021-07-19 14:18
Don't worry about the log. Now that I'm looking at the right piece of code, the problem is quite obvious.

**Comment by lonvia** [comment] 2021-07-26 08:58
I have increased the minimum required version for the 3.7.2 release to 9.5 now in the docs. If somebody needs 9.3/9.4 support and can provide a PR with fixes, I'm happy to do another release that decreases the requirement again. In the meantime, I'm closing this as 'fixed in documentation'.

**Closed by lonvia** 2021-07-26 08:58 UTC
