### ISSUE TITLE
"Toronto-Pearson, Canada" no longer works

### ISSUE THREAD

**Issue by endlisnis** [osm-search/Nominatim#2577] opened 2022-01-13 01:00 UTC
## What did you search for?
"Toronto-Pearson, Canada"

https://nominatim.openstreetmap.org/ui/search.html?q=Toronto-Pearson%2C+Canada

## What result did you get?

No search results found

## What result did you expect?

I expected it to find the Toronto Pearson airport, and it used to match before #2561 was fixed.

**Comment by lonvia** [comment] 2022-01-13 08:07
While it did give results before introducing #2565, it just returned some random schools and streets in the Toronto area and not the airport you are likely expecting.

This is another manifestation of the long-standing issue that searching of partial names does not work well. Closing as duplicate of #94.

**Closed by lonvia** 2022-01-13 08:07 UTC

**Comment by endlisnis** [comment] 2022-01-13 17:41
"Toronto-Pearson" still works, but does not match the airport either.  I find it strange that "Toronto-Pearson" works but if I add in a ", Canada" at the end, it stops working.  I guess it doesn't really matter because the results are not what I was looking for anyway.

**Comment by lonvia** [comment] 2022-01-13 18:27
Nominatim always tries two interpretations of your query: one along the line of 'street, city, country', the other reversed as 'country, city, street'. When you look for "Toronto Peason" (the hyphen is simply ignored), it will therefore look for a Toronto in Pearson and a Pearson in Toronto. You get results for the latter. Once you add "Canada" to the query, it becomes very obvious that the order you want is "street, city, country". So you won't get the reversed results anymore.

(In the end it should also be looking for a place with "Toronto" and "Pearson" in its name in a meaningful way. But that is a lot harder than it looks and the essence of the longstanding issue #94 that I linked.)
