### ISSUE TITLE
Result includes name of "far away" "suburb" of the address

### ISSUE THREAD

**Issue by osm-ToniE** [osm-search/Nominatim#3219] opened 2023-10-09 11:28 UTC
Link:

[Michael-Haslbeck-Straße 7](https://nominatim.openstreetmap.org/ui/search.html?q=michael-haslbeck-stra%C3%9Fe+7&polygon_threshold=0)

Result:

"7, Michael-Haslbeck-Straße, Putzbrunn, Waldkolonie, Putzbrunn, Landkreis München, Bayern, 85640, Deutschland"

Expected:

"7, Michael-Haslbeck-Straße, Putzbrunn, Landkreis München, Bayern, 85640, Deutschland"

Named wrongly: Yes

**Comment by mtmail** [comment] 2023-10-09 23:21
Usually Nominatim can link a place node with a boundary of the same name. But it helps when both have the same `wikidata` and `wikipedia` values, too.

Look at the nearby Grasbunn node (place=village, https://www.openstreetmap.org/node/67132969) and boundary (https://www.openstreetmap.org/relation/543185).

Try setting the `wikidata` and `wikipedia` values for the Putzbrunn node (place=village, https://www.openstreetmap.org/node/25631850)

**Comment by osm-ToniE** [comment] 2023-10-10 08:44
Hmm, that did not help, I guess.

Without the addr:housenumber, I get the following

https://nominatim.openstreetmap.org/ui/search.html?q=michael-haslbeck-stra%C3%9Fe&dedupe=0&bounded=1

where only the second result is correct w.r.t. Waldkolonie. It is the [short way](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=992158503&class=highway) at the bus stop to the east.

More far to [the east](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=25460489&class=highway), the street is identified to be in the "Gewerbegebiet Putzbrunn-Ost", which is OK f.m.p.o.v.

More far [to the west](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=25460416&class=highway), I can see the "greyed out" place:village "Oedenstockach" in the list, but not the closer place:village "Putzbrunn"

`Software version
    4.3.0-0
Database version
    4.3.0-0
Data last updated
    2023-10-10T08:39:41+00:00`

I modified place:village node "Putzbrunn" at `2023-10-10T07:57:00+00:00` or so.

**Comment by lonvia** [comment] 2023-10-10 13:48
This is essentially a duplicate of #2606, i.e. Waldkolonie and Putzbrunn are both `place=village` even though it looks like Waldkolonie is a suburb of Putzbrunn (admin_level=8). So closing here.

Be warned that this is very difficult to fix because OSM data is so inconsistent with respect to boundaries and place nodes. So don't expect any large improvements soon.

**Closed by lonvia** 2023-10-10 13:48 UTC
Labels: duplicate

**Comment by lonvia** [comment] 2023-10-10 15:44
I know that the situation is somewhat difficult with rural places.

One thing that works with Nominatim: elevate the [Putzbrunn place node](https://www.openstreetmap.org/node/25631850) to `place=municipality` to indicate that it is an artificial result of a "Gemeindefusion" of independent villages. This node would belong to the [level 8 boundary](https://www.openstreetmap.org/relation/56350). Then add another `place=village` node for Putzbrunn without any wikipedia/wikidata tag. This would be for the 'Gemeindeteil' Putzbrunn, the [level 10 boundary](https://www.openstreetmap.org/way/1136833572).

I'd go that route only, if the municipality is really an administrative construct only and the villages are still largely independent. If there is a clear main village that dominates the others, then using `place=hamlet` or `place=suburb` for the subordinates somewhat expresses things better.

Both solutions are in active use in rural Germany.

And, as I say, it's a difficult tagging situation, which is why #2606 remains open and to be solved one day.

**Comment by osm-ToniE** [comment] 2023-10-11 11:03
For Putzbrunn, I'll try place=suburb for the subordinates

For [Baiern](https://www.openstreetmap.org/relation/929923) for instance, we have already place=municipality, 'cause there is no such village/hamlet called "Baiern" over there.

Thanks!

**Comment by osm-ToniE** [comment] 2023-10-11 12:36
> For Putzbrunn, I'll try place=suburb for the subordinates

That did the magic and fixed the issue. Thanks!
