### ISSUE TITLE
Addresses with Ordinal Numbers Spelled Out

### ISSUE THREAD

**Issue by omagid-crp** [osm-search/Nominatim#2044] opened 2020-11-04 13:54 UTC
We have a lot of New York city addresses with ordinal numbers spelled out: "First" instead of "1st," "Second" instead of "2nd," etc. Nominatim is returning bad results for most of them. Here's one example. As you can see, it works fine if we replace "Second" with "2nd." We are dealing with user input, however. 

I would imagine this is a problem others have run into. Would we deal with it by replacing all spelled out ordinal numbers before searching with Nominatim?

URL: https://nominatim.openstreetmap.org/ui/search.html?q=96+Second+AVE+NEW+YORK+NY+10003
RESULT: 96, Second Avenue, Downtown Gloversville, Broadalbin Junction, Gloversville, Town of Johnstown, Fulton County, New York, 12078, United States of America (House)
EXPECTED RESULT: https://nominatim.openstreetmap.org/ui/search.html?q=96+2nd+AVE+NEW+YORK+NY+10003

**Comment by geoneutrino** [comment] 2020-11-04 16:25
There are already similiar issues with this - targeted for release 5.0 in planning board
https://github.com/osm-search/Nominatim/projects/1#card-42606826

i have observed this issue in several countries with variants. Not only ordinals ("counting") ist affected but also "normal" numbers used e.g. when the name contains a date like "Straße des 17. Juni" in Berlin or similar

In addition there can be grammar issues like 1st in french can be premier and also première

So we need good synonym tables for numbers in all languages, i don't know a central source on this
(OSRM Translations https://github.com/Project-OSRM/osrm-text-instructions/tree/master/languages/translations at least contains 1st to 10th in many languages)

**Comment by lonvia** [comment] 2020-11-05 21:29
Duplicate of #298.

**Closed by lonvia** 2020-11-05 21:29 UTC
Labels: duplicate
