### ISSUE TITLE
Search issue with addr:flats and addr:housename

### ISSUE THREAD

**Issue by osmuser63783** [osm-search/Nominatim#3327] opened 2024-02-05 00:37 UTC
Looks like Nominatim cannot deal with the combination of `addr:flats` + `addr:housename` (7 597 combinations), and possibly some similar patterns.

This is not a particularly common combination but it seems valid tagging to me, for example for a tower block or other building that has a name and no house number, and where number in the address just refers to the individual flat.

## What did you search for?

Example with addr:street
* [This search](https://nominatim.openstreetmap.org/ui/search.html?q=4+Wheatfield+Court%2C+Wheatfield+Street%2C+Lancaster) should return [this](https://www.openstreetmap.org/node/6498061128)
* [This search](https://nominatim.openstreetmap.org/ui/search.html?q=3+Bantock+House%2C+Parry+Road%2C+London) should return [this](https://www.openstreetmap.org/node/4608137755)

Example with addr:place
* [This search](https://nominatim.openstreetmap.org/ui/search.html?q=1+fontenelle+sceaux+gardens+London) should return [this](https://www.openstreetmap.org/way/595847006)

## What result did you get?

No results.

## Further details
Interestingly it works with housenumber, just not with house name.
* [This search](https://nominatim.openstreetmap.org/ui/search.html?q=1+17A+Mayes+Gardens+Manchester) returns [this](https://www.openstreetmap.org/way/1117430808)
* [This search](https://nominatim.openstreetmap.org/ui/search.html?q=111+3L+Osiedle+Zwyci%C4%99stwa+Pozna%C5%84) returns [this](https://www.openstreetmap.org/node/8482225599)

A variation of this issue, using `add:unit` instead of `flats` and `addr:block` instead of `housename`.
* [This search](https://nominatim.openstreetmap.org/ui/search.html?q=9+the+row++market+street+Hoylake) should return [this result](https://www.openstreetmap.org/node/9848694698)

Maybe it’s the general pattern of addresses that look at first glance like house number + street/place name?

**Comment by osmuser63783** [comment] 2024-02-05 00:41
Experimenting some more, the more common combination of `addr:unit` + `addr:housename` (18 234 uses) also does not work very reliably. Sometimes it [works](https://nominatim.openstreetmap.org/ui/search.html?q=8+Whiteleys+Parade) when you put just the unit and housename but [doesn't work](https://nominatim.openstreetmap.org/ui/search.html?q=8+Whiteleys+Parade%2C+Uxbridge+Road) as soon as you add the street name.

**Comment by lonvia** [comment] 2024-02-05 10:18
`addr:unit` and its variants `addr:flat` and `addr:flats` are not supported yet.

Duplicate of #587.

**Closed by lonvia** 2024-02-05 10:18 UTC
Labels: duplicate
