### ISSUE TITLE
Search issue with name_right and name_left issue

### ISSUE THREAD

**Issue by Fredhap** [osm-search/Nominatim#2803] opened 2022-08-22 21:22 UTC
## What did you search for?
From a PC, from this page: https://www.openstreetmap.org/#map=13/45.7649/4.8384
I searched "42 rue des docteurs cordier".

## What result did you get?
The result is this node: https://www.openstreetmap.org/node/2813884218
This result is wrong, this house being located at "42 rue Hector Berlioz".

## What result did you expect?
The right result is this node: https://www.openstreetmap.org/node/2813857495

After investigation, this issue might come from the name_left attribute of the segment of the correct node. 
I have to admit this segment is surprising with the different right and left names...

Thank you

**Comment by lonvia** [comment] 2022-08-29 14:25
The [associatedStreet relation](https://www.openstreetmap.org/relation/3681347), where node [2813884218](https://www.openstreetmap.org/node/2813884218) is part of, is broken. It contains [this street](https://www.openstreetmap.org/way/967775177). Fixing the relation will fix the name issue.

Closing as data issue.

**Closed by lonvia** 2022-08-29 14:25 UTC
Labels: data issue

**Comment by lonvia** [comment] 2022-08-29 14:28
Oh, sorry, I see what you mean with left/right. That makes the issue a combined duplicate of #2667 and #2183. So still leaving closed.
