### ISSUE TITLE
Add support for 'addr:flats'

### ISSUE THREAD

**Issue by wolterhv** [osm-search/Nominatim#3046] opened 2023-04-28 11:53 UTC
The [OSM Wiki article on the addr:flats key](https://wiki.openstreetmap.org/wiki/Key:addr:flats) describes how the attribute `addr:flats` may be used to encode the location of flats inside a building. It also suggests that a building with an arbitrary address X and the attribute `addr:flats` set to something like `1;3;7-9` may be used to resolve the addresses "Flat 1,  X", "Flat 3, X", "Flat 7, X", "Flat 8, X" and "Flat 9, X". It would be very nice if Nominatim could support this.

I propose that Nominatim support resolving addresses of the form "Y, X", where

* X is an address of the type currently supported by Nominatim (e.g. "16 Wimbledon Park, Huckleton, UK" or "Wurmstrasse 12, Bamburg, DE") and 
* Y is a string of the form "CODE", "WORD CODE" or "CODE WORD" where CODE is a code deemed to be included by the value of `addr:flats` and WORD is a string that Nominatim can ignore.

**Comment by wolterhv** [comment] 2023-04-28 11:53
This is possibly related to #587.

**Comment by lonvia** [comment] 2023-04-28 12:34
This is indeed pretty much a duplicate of #587, so closing here.

No ETA at the moment, sorry.

**Closed by lonvia** 2023-04-28 12:34 UTC
Labels: duplicate
