### ISSUE TITLE
Part of addresses in Rzeszów (Poland) assigned to neighbouring community of Tyczyn although within relation of Rzeszów

### ISSUE THREAD

**Issue by szydzio** [osm-search/Nominatim#2007] opened 2020-10-10 16:59 UTC
Searching some addresses in eastern Rzeszów (Poland) that are close to the border of community of Tyczyn localise them within the village of Kielnarowa/community of Tyczyn although they are physically within the borders (relation) of Rzeszów and all have the tag addr:city=Rzeszów

https://www.openstreetmap.org/search?query=Rzesz%C3%B3w%2C%20Matysowska%20150#map=19/49.99052/22.07129

https://www.openstreetmap.org/search?query=Rzesz%C3%B3w%2C%20Pieni%C5%84ska%2012#map=19/49.99093/22.06873

**Comment by mtmail** [comment] 2020-10-10 22:54
The road https://www.openstreetmap.org/way/755422487 touches the border of two cities. I believe that got fixed in https://github.com/osm-search/Nominatim/pull/1902 already and just needs the region to get reindex.

https://nominatim.openstreetmap.org/search.php?q=Rzeszów,Matysowska+150&format=jsonv2&addressdetails=1&pretty=1
```
[...]
        "display_name": "150, Matysowska, Góra, Matysówka, Kielnarowa, gmina Tyczyn, powiat rzeszowski, województwo podkarpackie, 35-330, Polska",
        "address": {
            "house_number": "150",
            "road": "Matysowska",
            "hamlet": "Góra",
            "suburb": "Matysówka",
            "village": "Kielnarowa",
            "municipality": "gmina Tyczyn",
            "county": "powiat rzeszowski",
            "state": "województwo podkarpackie",
            "postcode": "35-330",
            "country": "Polska",
            "country_code": "pl"
        }
 [...]
```

On a server I installed after the fix I get

```
  "display_name": "150, Matysowska, Matysówka, Rzeszów, Kielnarowa, gmina Tyczyn, powiat rzeszowski, województwo podkarpackie, 35-330, Polska",
        "address": {
            "house_number": "150",
            "road": "Matysowska",
            "suburb": "Matysówka",
            "city": "Rzeszów",       <===
            "village": "Kielnarowa",
            "municipality": "gmina Tyczyn",
            "county": "powiat rzeszowski",
            "state": "województwo podkarpackie",
            "postcode": "35-330",
            "country": "Polska",
            "country_code": "pl"
        }
```

**Comment by lonvia** [comment] 2020-10-11 08:20
We still need #328 to get that fixed correctly. The city is already [in the address list](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=311962065&class=building), it just doesn't get picked.

Closing as duplicate of #328.

**Closed by lonvia** 2020-10-11 08:20 UTC
Labels: duplicate
