### ISSUE TITLE
The search does not work after installation

### ISSUE THREAD

**Issue by dmitrymaslov99** [osm-search/Nominatim#2387] opened 2021-07-09 07:31 UTC
Installed using the command - nominatim import --osm-file <data file> 2>&1 | tee setup.log
No additional flags were set. The reverse script works fine, the search does not work. Returns the following error:
![image](https://user-images.githubusercontent.com/36110676/125040843-bfab5d00-e0a0-11eb-8479-6fa719f5a67c.png)

**Comment by lonvia** [comment] 2021-07-09 07:37
Please use the [appropriate Issue template](https://github.com/osm-search/Nominatim/issues/new?assignees=&labels=&template=report-problems-with-the-software.md&title=) and fill out all requested information. In particular include all steps necessary to reproduce the observed behaviour.

Closing because the issue report lacks essential information.

**Closed by lonvia** 2021-07-09 07:37 UTC
