### ISSUE TITLE
Full GB postcode ignored for London, UK address

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2988] opened 2023-02-25 10:20 UTC
## What did you search for?

13 Heber Road, London, NW2 6AB

https://nominatim.openstreetmap.org/ui/search.html?q=13+Heber+Road%2C+London%2C+NW2+6AB

## What result did you get?

13 Heber Road, East Dulwich, London Borough of Southwark, London, SE22 9JZ

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=106895584&class=building

## What result did you expect?

Somewhere around Heber Road, London Borough of Brent, London, NW2 6AB

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=4075249

Near 51.5549846,-0.2192094

## Further details

The housenumber is not in OSM data

`location_postcodes` table contains `NW2 6AB,51.55531,-0.21944`

**Comment by lonvia** [comment] 2023-02-25 15:52
Duplicate of #2771.

**Closed by lonvia** 2023-02-25 15:52 UTC
Labels: duplicate
