### ISSUE TITLE
Cafe in Marseille, Spain is assigned country_code=gb

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2688] opened 2022-05-01 22:19 UTC
## What did you search for?

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=8405358832&class=shop

https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=3443644793

## What result did you get?

Both are assigned to Rufus Close https://www.openstreetmap.org/way/8149235 in England. The address hierarchy then assignes a GB county, postcode, country code.

## What result did you expect?

Country code in Spain.

## Further details

https://www.openstreetmap.org/way/8149235 points to Rufus Close
https://www.openstreetmap.org/relation/8149235 points to the market square Marseille
so I think it's an issue in the indexing.

I tested using new European import using Nominatim master branch (https://github.com/osm-search/Nominatim/commit/439d175) so I think the issue is still present on master.

**Comment by lonvia** [comment] 2022-05-02 07:27
Duplicate of #2669. Closing here.

**Closed by lonvia** 2022-05-02 07:27 UTC
