### ISSUE TITLE
Ignorable segment of a query string may break search

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim#1866] opened 2020-07-01 21:52 UTC
`MLYNARSKA 42, Warszawa` works perfectly, despite that searched string is not perfect

https://www.openstreetmap.org/search?query=MLYNARSKA+42%2C+Warszawa#map=19/52.23989/20.97150

and finds https://www.openstreetmap.org/way/195211505 as expected

`UL.MLYNARSKA 42, Warszawa` sadly finds an incorrect object ("ul." is shortened form of "ulica" meaning "street" in Polish and should not break address search)

https://www.openstreetmap.org/search?query=UL.MLYNARSKA%2042%2C%20Warszawa#map=19/52.23752/20.97199

finds https://www.openstreetmap.org/node/4584575811 what is not completely wrong but also not the correct match

Data is from a real data source - database of locations of voting places during national elections in Poland, from PKW (państwowa komisja wyborcza - national election commission).

**Comment by matkoniecz** [comment] 2020-07-01 21:57
I am currently working on processing query strings to remove unneded parts confusing Nominatim. If that it would be useful I may also create issues for cases where more complicated or less obvious processing was needed, though I am unsure whatever I am capable of making pull requests.

**Comment by lonvia** [comment] 2020-07-02 07:49
Duplicate of #145.

NB: The Polish tagging is really odd. You have the designation for counties, states etc even with translations into multiple languages (e.g. https://www.openstreetmap.org/relation/2675551) but you leave out the 'ulica'?

**Closed by lonvia** 2020-07-02 07:49 UTC

**Comment by matkoniecz** [comment] 2020-07-02 08:16
> but you leave out the 'ulica'?

Yes, this is a part of a tagging standards in Poland - and one of the most consistently applied ones. And it is typical in map making in Poland (see Goggle Maps or https://mapy.geoportal.gov.pl/imap/Imgp_2.html?gpmap=gp0 - the national government website)

> You have the designation for counties, states etc

Yes, administrative boundaries are well mapped in Poland.

>  even with translations into multiple languages 

I am a bit dubious about that but I never really investigated this.

**Comment by lonvia** [comment] 2020-07-02 10:02
> It is fairly standard to leave out "Ulica" but keep spceial types ("Alley" - "Aleja", "Square" - "Plac" and so on)

It's a pain for a data user. Because a) you have to know that this rule needs to be applied in a certain geographic area (the Polish community might know but not every data user can figure that out) and b) it's a complicated rule: if there is no word that might otherwise designate the type (aleja, plac, ...) then please add 'ulica'. Especially the part where you have to figure out if the type is included or not invoves lots of guessing. It is always easier to remove something from a name than to guess when to add it.

> It is fairly standard to leave out "Ulica" but keep spceial types ("Alley" - "Aleja", "Square" - "Plac" and so on)

It's a standard for map display maybe but apparently not when you ask the geocoder. Otherwise you would not have opened the ticket. So the tagging clearly prefers one over the other.

**Comment by matkoniecz** [comment] 2020-07-02 10:50
> if there is no word that might otherwise designate the type (aleja, plac, ...) then please add 'ulica'. 

Not exactly, because it is even more common to search for address without specifying "ulica" / "ul" / "ul." part.

It is rather "always ignore "ulica" / "ul" / "ul." prefix for searches in Poland".

> It's a standard for map display maybe but apparently not when you ask the geocoder. 

I would say that it is standard to skip it also when searching the address - main issue is that map rendering outputs something, while geocoder users expect it to deal with all kinds of malformed data.

Entries with extraneous gibberish, overly specified addresses, misspellings, shortened street addresses or all of that at once.

So it is more of "user input handling" issue.
